README.md
The libx11-dev and libxkbfile-dev packages were required when we had the atom-keymap npm dependency. This was removed a while ago, so we no longer need these packages when installing on Linux.
=> Remove redundant Linux dependencies in README

README.md
The electron npm package is no longer called "electron-prebuilt", but just "electron". Updating the docs accordingly.
=> Rename from electron-prebuilt to electron in README instructions

README.md, index.js, lib/windows/plugin/actions/mainMenuActions.js, lib/windows/plugin/components/MainMenu.jsx, lib/windows/plugin/components/NavBar.jsx, lib/windows/plugin/components/SerialPortSelector.jsx, lib/windows/plugin/components/__tests__/MainMenu-test.jsx, lib/windows/plugin/components/__tests__/SerialPortSelector-test.jsx, lib/windows/plugin/components/__tests__/__snapshots__/MainMenu-test.jsx.snap, lib/windows/plugin/components/__tests__/__snapshots__/SerialPortSelector-test.jsx.snap, lib/windows/plugin/containers/MainMenuContainer.js, resources/css/styles.less, test/mainMenu-test.js, test/serialPortSelector-test.js
Adding a main menu dropdown button in the top-left corner. It currently only contains a "Plugin manager..." item that will open a window for loading/managing plugins. The plugin manager window has not been implemented yet, but is next on the agenda.
=> Add main menu dropdown in the top-left corner

lib/components/ConfirmationDialog.jsx, lib/windows/app/components/FirmwareDialog.jsx, lib/windows/app/containers/FirmwareDialogContainer.js
When user selects a serial port but chooses to cancel the firmware dialog, the serial port is still selected.
=> Select the serial port in case firmware is not to be burned

lib/api/probe/__tests__/index-test.js, lib/api/probe/index.js, lib/api/programming/__tests__/index-test.js, lib/api/programming/index.js, package.json
Making it possible for apps to read devkit family and custom memory addresses for a given serial number. This can be used by apps to detect if the required firmware is present, and not show the firmware dialog if it is not needed.
Example app that reads 10 bytes from address 0 and logs it when the user selects serial port:
```
function readAddress(port) {
return (dispatch, getState, { programming, logger }) => {
const address = 0;
const length = 10;
programming.readAddress(port.serialNumber, address, length)
.then(dataArray => logger.info(`Got data: ${dataArray}`));
};
}
export default {
mapSerialPortSelectorDispatch: (dispatch, props) => ({
...props,
onSelect: port => dispatch(readAddress(port)),
}),
};
```
=> Add API functions for reading address and family

lib/windows/app/reducers/__tests__/appReducer-test.js
Apps can implement `reduceApp` to manage their own custom state.
```
export default {
reduceApp: (state, action) => {
/* reducer logic */
},
};
```
Normally, Redux reducers receive `undefined` as state when invoked for the first time. This is commonly used as a convention for specifying the initial state, like this:
```
export default {
reduceApp: (state = { foo: 'bar' }, action) => {
/* reducer logic */
},
};
```
This did not work for `reduceApp`. It received `{}` as state when invoked for the first time, which made it difficult for apps to set their own initial state. This has now been fixed so that state is `undefined` on the first invocation.
=> Allow apps to set initial state in reduceApp

lib/api/yarn/__tests__/parsing-test.jsx, lib/api/yarn/index.js, lib/api/yarn/parsing.js, lib/util/fileUtil.js, package.json
We are going to add a UI for installing/removing apps. The apps will be published on npmjs.org, which means that we can use npm or yarn to manage packages. The plan is to have the following directory structure in the user's home directory:
```
~/.nrfconnect-apps
├── local                   # Used during development, or for unofficial apps
|   └── pc-nrfconnect-foo
├── node_modules            # Installed npm packages, as specified by package.json
│   ├── pc-nrfconnect-ble
│   └── pc-nrfconnect-rssi
├── package.json            # Specifies which apps we have installed, and their version
└── apps.json               # List of official apps that may be installed
```
This PR adds the possibility to install, remove, upgrade, and check for updates for npm packages in the ~/.nrfconnect-apps …
=> Add wrapper for installing apps using yarn

.gitignore, main/apps.js, test/features/one-local-app/node_modules/.gitignore, test/features/one-official-app-installed/node_modules/pc-nrfconnect-test/index.js, test/features/one-official-app-installed/node_modules/pc-nrfconnect-test/package.json, test/features/one-official-app-not-installed/node_modules/.gitignore, test/features/one-official-app-upgradable/node_modules/pc-nrfconnect-test/index.js, test/features/one-official-app-upgradable/node_modules/pc-nrfconnect-test/package.json
Fixed some incorrect path separators in `main/apps.js`.
Also, now only excluding `node_modules` in the root of the repo. There are some node_modules directories below `test/` that are needed for integration tests, so added those.
=> Fix path separator issue when reading app info

lib/windows/app/index.js
As apps exist outside of core, they cannot import modules from core's node_modules directory. What happens when apps do 'import React from "react"' is that it tries to load react from the app's node_modules directory.
One might think that this would work as long as the app actually has react as a dependency. However, if core loads react from its node_modules directory, and the app loads react from a different node_modules directory, react will complain about multiple copies of react being loaded at the same time. A similar issue happens with react-redux.
To fix this, we must make sure that the imported react and react-redux instances are the same for both core and the app. Monkey patching Module._load isn't pretty, but I have not been able to find a better way to do it. Got the idea from …
=> Avoid issues with multiple copies of react and react-redux

README.md, lib/util/__tests__/apps-test.jsx, lib/util/apps.js, lib/windows/app/actions/firmwareDialogActions.js, lib/windows/app/containers/FirmwareDialogContainer.js, lib/windows/app/containers/SerialPortSelectorContainer.js, lib/windows/app/reducers/__tests__/firmwareDialogReducer-test.js, lib/windows/app/reducers/firmwareDialogReducer.js
Up until now, core has opened the firmware dialog when selecting serial port, and done programming based on `config.firmware*` settings provided by the app. The intention behind this was to make things easy for apps, and to provide a common default. However, I see some problems with this approach:
- A common use case is to only show the firmware dialog if programming is necessary. Then the apps most likely have to override the default anyway.
- When selecting serial port, I would expect the `SERIAL_PORT_SELECTED` action to be dispatched, but it is currently dispatching `FIRMWARE_DIALOG_SHOW`. This may be confusing.
- We have had some discussions lately on what core should do and not do, and @CoqRogue argued that core should be simple, and not add extra logic on top of external libraries …
=> Not show firmware dialog by default

package.json
When electron-builder detects that it is running on a CI server, it will use publishing configuration `onTagOrDraft`, ref: https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts#cli-flags.
When `onTagOrDraft` is enabled, it tries to connect to GitHub to see if there is a draft release. If that is the case, the artifacts are added to the draft release. This may be useful in the future, but right now we do not have a GitHub token set up on the build server, so connecting to GitHub fails. Switching publishing off until we are ready to publish.
=> Explicitly tell electron-builder to not publish artifacts

package.json
Changing to depend on the master branch of pc-ble-driver-js while we are working on nRF Connect 2.0. This branch contains some new features, such as getting firmware path/content.
The pc-ble-driver-js master branch will be tagged with a new version before release, so we should update this dependency when that time comes.
=> Refer to pc-ble-driver-js master during development

README.md, build/get-nrfjprog.js, package.json
This replaces the manual `npm run get-nrfjprog && cp ...` step that was previously required on Linux and macOS. Now the nrfjprog libraries are set up automatically after `npm install`.
=> Copy nrfjprog libs to electron directory in node_modules

package.json
Our current version of yarn caches each module it requires. When it runs, it stores a map of required paths, with their corresponding location on the file system. It uses a library called roadrunner for doing this, and the file is put in the user's home directory.
This causes problems for us, as when we release new versions of nRF Connect, the modules can be shuffled around, and the yarn cache ends up being invalid.
In the version 0.24.x of yarn, it appears that roadrunner has been removed. Upgrading, so that we can avoid this caching issue.
=> Upgrade to yarn 0.24.2

lib/windows/app/reducers/__tests__/serialPortReducer-test.js
The build started failing after merging #64 to master. This PR fixes the issue.
The logger and serialport are not dependency injected into action creators anymore, but imported directly. This means that we have to mock them in unit tests. This is because they depend on things like Node.js addons and electron, which is not available during unit testing.
=> Mock serialport and logger in serialPortReducer-test.js

build/installer.nsh, index.js, lib/components/ConfirmationDialog.jsx, lib/windows/launcher/actions/autoUpdateActions.js, lib/windows/launcher/components/UpdateAvailableDialog.jsx, lib/windows/launcher/components/UpdateProgressDialog.jsx, lib/windows/launcher/components/__tests__/UpdateProgressDialog-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/UpdateProgressDialog-test.jsx.snap, lib/windows/launcher/containers/UpdateAvailableContainer.js, lib/windows/launcher/containers/UpdateProgressContainer.js, lib/windows/launcher/index.js, lib/windows/launcher/reducers/__tests__/autoUpdateReducer-test.js, lib/windows/launcher/reducers/autoUpdateReducer.js, lib/windows/launcher/reducers/index.js, main/autoUpdate.js, main/config.js, package.json, test/oneLocalApp-test.js, test/oneOfficialAppInstalled-test.js, test/oneOfficialAppNotInstalled-test.js, test/oneOfficialAppUpgradable-test.js, test/setup/index.js
At startup, nRF Connect will now check for new releases on GitHub. If a new release is available, this will pop up in the launcher window:
When clicking "Yes", it will start downloading the new version:
I had to make some adjustments for macOS, as download progress and cancel is not supported there:
When the download is complete, nRF Connect exits, the new version is installed, and nRF Connect is started again.
=> Auto update for Windows and macOS

package.json
When running spectron, it prints 'WARNING: the "timeoutsAsyncScript" command will be depcrecated soon'. Upgrading to the latest version to get rid of the warning.
=> Upgrade spectron to avoid deprecation warning

build/get-nrfjprog.js, package.json
Building pc-ble-driver-js fails on build servers after upgrading tar from v2 to v3. Reverting to v2 to avoid the issue.
=> Revert to tar v2.2.1 due to cmake-js incompatibility

index.js, main/config.js, package.json, test/oneLocalApp-test.js, test/oneOfficialAppInstalled-test.js, test/oneOfficialAppNotInstalled-test.js, test/oneOfficialAppUpgradable-test.js, test/setup/index.js
The minor version of spectron has to match the minor version of electron. This is because spectron comes with electron-chromedriver, which must be compatible with the electron version we are using. More info: https://www.npmjs.com/package/spectron.
Also skipping the splash screen in integration tests now. It seems to cause some random "window not available" errors when calling `windowByIndex()`.
=> Fix spectron version incompatibility

package.json, webpack.config.js
Up until now, we have added all dependencies as externals. This is convenient as we do not have to manually specify which libs should be external. However, it comes with a performance penalty.
When opening the browser window, all require's of the web page are processed. If the application needs to load required modules from node_modules, then it first needs to figure out where the module exists on the file system, then open the files, and finally parse them.
If we bundle as much as possible into dist/ at build time, then the application can skip a lot of the resolving/opening of files at runtime. In my Windows VM this reduces the loading time of apps from ~2.2 sec to ~1.5 sec.
It does, however, cause webpack to use more time when building. We could consider only doing this for production …
=> Bundle as much as we can with webpack to reduce loading time

package.json
There was a bug in electron-builder that caused symlinks to be broken in the tar.gz release artifact. We are including nrfjprog libraries with symlinks, and as a result, nrfjprog did not work. I submitted a pull request for electron-builder that fixes the issue: https://github.com/electron-userland/electron-builder/pull/1614.
Upgrading to the latest version, where the symlink fix is included.
=> Upgrade electron-builder to fix broken symlinks

lib/windows/launcher/actions/autoUpdateActions.js, lib/windows/launcher/components/UpdateProgressDialog.jsx, lib/windows/launcher/components/__tests__/UpdateProgressDialog-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/UpdateProgressDialog-test.jsx.snap, lib/windows/launcher/containers/UpdateProgressContainer.js, lib/windows/launcher/reducers/__tests__/autoUpdateReducer-test.js, lib/windows/launcher/reducers/autoUpdateReducer.js, package.json
The latest electron-builder release adds download progress status when doing auto-update on macOS:
https://github.com/electron-userland/electron-builder/releases/tag/v18.5.1
This means that we can now show the progress bar in the UpdateProgressDialog, similar to what we are doing on Windows.
=> Show download progress during auto-update on macOS

index.js, main/menu.js
Application menu only has effect when set after app is 'ready'.
Also template is simplified, on mac File menu is equivalent to 'Electron'.
=> set app menu when app is ready

lib/windows/app/reducers/__tests__/serialPortReducer-test.js, lib/windows/app/reducers/serialPortReducer.js, package.json
The name `serialNumber` implies that this is a number, not a string. Also, pc-nrfjprog-js and pc-ble-driver-js expects a number when passing the serial number as a parameter.
=> Store serial numbers as integers

resources/css/app.less
Found a bug in the style sheet. Errors had the same styling as regular log messages, but should be highlighted with red color.
=> Fix different styling for errors in log viewer

build/get-nrfjprog.js, build/installer.nsh, package.json
The NSIS installer only checked if nrfjprog was not installed, and ran the nrfjprog installer based on this. Now also running the nrfjprog installer if the installed version is older than the one we are bundling.
=> Check nrfjprog version in NSIS installer

package.json
The new pc-nrfjprog-js version comes with tar files and installers for nRF5x-Command-Line-Tools. When we npm install pc-nrfjprog-js, these files are included, and added to node_modules. When creating release artifacts, this adds an extra ~30 MB to the artifact size, which we do not need.
To avoid this, I am configuring electron-builder to ignore the given directory.
=> Exclude unnecessary nrfjprog files from release artifacts

package.json
The pc-nrfjprog-js v1.0.1 does not work as expected, so rolling back to v1.0.0. The v1.0.1 waits for 500 ms before returning after performing operations, to make sure the serial port is ready. However, this does not seem to make any difference.
=> Revert from pc-nrfjprog-js v1.0.1 to v1.0.0

apps.json, package.json
Also bumping to 2.0.0-rc.0, as we are getting close to release.
=> Set correct name for the Bluetooth low energy app

lib/windows/app/components/__tests__/FirmwareDialog-test.jsx, lib/windows/launcher/components/AppIcon.jsx, lib/windows/launcher/components/InstalledAppItem.jsx, lib/windows/launcher/components/__tests__/AppLaunchView-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/AppLaunchView-test.jsx.snap, lib/windows/launcher/components/__tests__/__snapshots__/AppManagementView-test.jsx.snap, package.json, resources/css/launcher.less
The launcher now shows an information icon with a tooltip text when upgrades are available.
Also added "Installed" and "Upgrade available" labels in the "Add/remove apps" screen to make it more obvious what the status is.
=> Improve app installation status in launcher

lib/windows/app/actions/serialPortActions.js, lib/windows/app/components/SerialPortSelector.jsx, lib/windows/app/components/__tests__/SerialPortSelector-test.jsx, lib/windows/app/components/__tests__/__snapshots__/SerialPortSelector-test.jsx.snap, lib/windows/app/reducers/__tests__/serialPortReducer-test.js, lib/windows/app/reducers/serialPortReducer.js
Moved functionality of filtering serial ports by SEGGER vendor id to SerialPortSelector components filterPort() property function which can be overloaded by apps to access all/any serial ports.
=> Introduced overloadable serial port filter

main/browser.js
By default, when the user drags and drops a file into the browser window, it navigates away from our web application. Preventing this by overriding the default "will-navigate" event, ref:
https://discuss.atom.io/t/prevent-window-navigation-when-dropping-a-link/24365
=> Do not navigate when user drags and drops file

lib/windows/launcher/actions/proxyActions.js, lib/windows/launcher/components/ProxyErrorDialog.jsx, lib/windows/launcher/components/Root.jsx, lib/windows/launcher/containers/ProxyErrorContainer.js, lib/windows/launcher/reducers/proxyReducer.js
If the user is behind a proxy that requires authentication, and cancels the proxy login dialog, then app installation and checking for updates will fail. Showing some (hopefully) helpful text to the user in this situation, so that the user can disable checking for updates at startup and install apps manually instead.
=> Show information dialog if proxy login is cancelled

lib/components/ConfirmationDialog.jsx, lib/components/__tests__/ConfirmationDialog-test.jsx, lib/components/__tests__/__snapshots__/ConfirmationDialog-test.jsx.snap, lib/windows/launcher/actions/settingsActions.js, lib/windows/launcher/components/SettingsView.jsx, lib/windows/launcher/components/UpdateCheckCompleteDialog.jsx, lib/windows/launcher/components/__tests__/SettingsView-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/SettingsView-test.jsx.snap, lib/windows/launcher/containers/SettingsContainer.js, lib/windows/launcher/reducers/__tests__/settingsReducer-test.js, lib/windows/launcher/reducers/settingsReducer.js
Up until now there has been no feedback to the user after pressing the "Check for updates now" button in the Settings screen. Now popping up a dialog after the update check is complete, showing "All apps are up to date" or "One or more updates are available. Go to the Add/remove apps screen to upgrade".
=> Show dialog after manual check for updates

main/net.js
When the user enters proxy credentials, they are cached in a session so that they do not have to be entered again. We have been using the default session from Electron. However, the electron-updater library performs network requests with a different session, using the ["electron-updater" session name](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts). This means that proxy credentials have to be submitted twice - once for each session. To avoid this, we can use the same session that electron-updater is using for our own network requests.
We could consider adding a feature/pull request for electron-updater that allows configuring which session to use, which would be a cleaner solution in our case.
=> Use the same session name as electron-updater

lib/windows/launcher/actions/appsActions.js, lib/windows/launcher/actions/autoUpdateActions.js, lib/windows/launcher/actions/settingsActions.js, lib/windows/launcher/containers/SettingsContainer.js, lib/windows/launcher/index.js, lib/windows/launcher/reducers/__tests__/settingsReducer-test.js
When the "Check for updates now" button is pressed, we check for both app updates and core updates. If the user is behind a proxy that requires authentication, then we cannot send the requests in parallel, because that would result in HTTP 407 responses for both requests.
We need to send one request first, which receives a HTTP 407, and allow the user to enter proxy credentials for that request. The next request will then use the cached credentials.
=> Fix proxy server issue with "Check for updates now" button

main/__tests__/fileUtil-test.js
After fs-extra was introduced in fileUtil.js, the unit tests started failing with error "TypeError: polyfills is not a function". Not sure why. The application still works as expected, so it seems to be related to the jest runtime. Mocking fs-extra as it is not relevant for the tests.
=> Mock fs-extra in fileUtil-test.js

main/config.js, main/windows.js, package.json
The `__dirname/../` approach apparently did not work when specifying the path to window title icons. The icons were displayed when running the application in development mode, but not when running the packaged version. This is probably related to asar. Using config method for locating the resources directory instead.
=> Fix issue with window icons not being displayed

build/get-nrfjprog.js, build/installer.nsh, package.json
Upgrade the pc-nrfjprog-js dependency to v1.1.0. Also upgrading the bundled nRF5x-Command-Line-Tools to v9.7.1.
=> Upgrade to pc-nrfjprog-js v1.1.0 and command line tools v9.7.1

lib/api/registry/reg.js
When finding JLink serial numbers in Windows registry, a recursive search is performed below `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USB` to find `PortName` and `ParentIdPrefix` values.
By default, the reg.exe command searches all registry types. However, we are only interested in string values (REG_SZ). Adding `/t REG_SZ` to the query command can improve query performance significantly in cases where the user has a lot of non-string entries in the registry.
=> Improve JLink serial number lookup time on Windows

lib/windows/app/actions/serialPortActions.js, package.json
In some cases, JLink devices stop functioning and become impossible to open. This typically happens when a JLink device has been connected to a Windows PC overnight (related to MSD). The only workaround is to power cycle the device.
When trying to perform operations with nrfjprog when the device is in this state, it will fail silently with no feedback to the user. At the moment, the only reliable way to check if a device is actually available is to try to open it with serialport.
=> Verify that serial port is not dead when selected

lib/api/core/index.js, lib/api/logging/index.js, lib/util/apps.js, lib/windows/app/actions/logActions.js, lib/windows/app/index.js, main/fileUtil.js, main/mkdir.js
Basename of appPath is used to create separate directories under so far common logdir in order to separate the similarly named logfiles.
Update:
The context of this PR changed slightly, for apps, the core initilizes
`...<userDataDir>/<appName>` as *appDataDir* and `...<userDataDir>/<appName>/logs` as *appLogDir*. We decided separate *config* directory is not needed, so that is now skipped.
=> Separate data and logging directories for apps

resources/css/app.less
When there is some wide content in the main view, the side panel is pushed to the right and may end up being too narrow or hidden. Applying this `min-width: 0` flexbox trick that @bencefr used for one of the apps. This keeps the side panel visible, and adjusts the size of the main view instead. If the contents of the main view cannot be made narrower, f.ex. in the BLE app if there are many connections, then a horizontal scrollbar is shown in the main view.
For more info on this approach, see: https://css-tricks.com/flexbox-truncated-text/
Before fix:
After fix:
=> Fix side panel resize issue

main/apps.js
In case a new tgz package is found in local app directory while the same app is already installed, the user is now offered that the old app can be removed, thus avoiding required user action outside of the application.
=> Added confirmation and removal of old local app upon extract

package.json
Now that pc-ble-driver-js has been published to npm and includes precompiled binaries, this project should install a lot faster.
Also good to use the opportunity to test the precompiled binaries during development some time before the next pc-nrfconnect-core release.
=> Use pc-ble-driver-js from npm with precompiled binaries

lib/api/registry/index.js, lib/api/registry/reg.js, lib/windows/app/actions/serialPortActions.js, package.json
On Windows, we perform a lookup in the registry to find J-Link serial numbers for COM ports. There are some weaknesses with this approach as described in [lib/api/registry/index.js](https://github.com/NordicSemiconductor/pc-nrfconnect-core/blob/4b33f532d157e47ccae26b60a67b89d6b1d7ff22/lib/api/registry/index.js). Multiple serial numbers may be returned, and we do not know which one to use. Up until now, we have just picked the highest number.
When getting multiple serial numbers, we now invoke pc-nrfjprog-js to detect which one is actually connected. Calling pc-nrfjprog-js will slow down listing of the serial ports, so we only do it when required.
=> Handle edge cases in J-Link serial number lookup

lib/api/jlink/__tests__/jlinkFacade-test.js, lib/api/jlink/jlinkFacade.js, lib/windows/app/actions/serialPortActions.js, mocks/nrfjprogjsMock.js, package.json
In #145, we added a mechanism for querying pc-nrfjprog-js when multiple serial numbers exist for a COM port in Windows registry. This worked fine as long as there was only one COM port that had multiple serial numbers. However, when multiple ports have multiple serial numbers, pc-nrfjprog-js was called multiple times in parallel. This crashed the application, as pc-nrfjprog-js does not support multiple operations in parallel.
The logic around this started to get a bit complicated, so I have now extracted the serial number lookup routine for Windows into a JlinkFacade. This combines registry lookup with connected devices from pc-nrfjprog-js to identify which serial number to use.
=> Further improve serial number lookup routine on Windows

test/offline/oneLocalApp-test.js
Here we are trying to click an element that may not be visible yet. The build failed on the CI server today because of this. Adding `waitForVisible` to make sure that the element is visible before clicking.
=> Fix timing issue in spectron test by using waitForVisible

main/config.js
When the application is started as an AppImage, it mounts the image in /tmp and executes the application from there. The `electronApp.getPath('exe')` then returns the path to the executable
inside the mounted image. This is just a temporary path, so when the application is restarted, the path to the executable in /tmp will be different.
We need a more reliable path to the executable, as this is the path that we refer to when creating app shortcuts. When being run as an AppImage, the application will have an `APPIMAGE` environment variable that points to the path of the AppImage file. Using that as executable path if it is set, so that
shortcuts point to the right place.
=> Make app shortcuts work when using AppImage

.npmrc, package.json
Upgrading electron to get the latest patches for 1.6.
We should also consider upgrading to the latest minor version, but while the electron API is following semver (no breaking changes before 2.0), the bundled Node.js and Chrome versions may introduce breaking changes. Also, upgrading to the latest minor would require publishing new binaries for pc-ble-driver-js and pc-nrfjprog-js.
=> Upgrade to electron 1.6.16

lib/components/ConfirmationDialog.jsx, lib/components/__tests__/__snapshots__/ConfirmationDialog-test.jsx.snap, lib/windows/launcher/components/UpdateAvailableDialog.jsx, lib/windows/launcher/components/UpdateCheckCompleteDialog.jsx, lib/windows/launcher/components/__tests__/__snapshots__/SettingsView-test.jsx.snap, lib/windows/launcher/containers/UpdateAvailableContainer.js, main/config.js, resources/css/launcher.less
A link to nRF Connect release notes was added in #148, but it was added to the wrong dialog. There is one dialog that informs the user if there are app updates after clicking "Check for updates now", and one that pops up by itself if the auto-update mechanism detects a new core version. The latter is where we want the link to be, so I have moved it there.
The components were poorly documented, and can I understand that this was confusing. Added some documentation for the components to make it more clear. Also changed the link so that it opens the release notes in the user's default browser instead of an Electron browser window.
=> Show link to releases when asking for core update

lib/windows/launcher/actions/autoUpdateActions.js, lib/windows/launcher/components/UpdateProgressDialog.jsx, lib/windows/launcher/components/__tests__/UpdateProgressDialog-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/UpdateProgressDialog-test.jsx.snap, lib/windows/launcher/containers/UpdateProgressContainer.js, lib/windows/launcher/reducers/__tests__/autoUpdateReducer-test.js, lib/windows/launcher/reducers/autoUpdateReducer.js
The electron-updater does not emit progress updates when downloading on Linux. Showing a spinner instead of the progress bar.
=>  Do not show progress during Linux auto updates

lib/windows/launcher/actions/desktopShortcutActions.js
- Windows is not capable of correctly displaying PNG based .ico files, generating BMP based ones instead
- Condition to check for pregenerated icons fixed
=> Fixed app icon generation issues

package.json
When updating the application on Windows 7 the progress bar showed 100% for 30 seconds before restarting and installing the update. This was due to a bug in electron-updater, which has been fixed in v2.20.2.
=> Fix long delay during update on Windows 7

apps.json
- Previous PR had the old npm repository location.
=> Move npm location for nRF Cloud Gateway (again)

package.json
Also now using semver caret in dependency, so that we get new patch or minor versions automatically.
=> Update devdep version to fix jsx linting issue

README.md
The #semver syntax used for the devdep dependency is only supported by recent versions of npm/yarn. Updating the README.
=> Update npm/yarn requirement in README

lib/windows/app/components/DeviceSelector.jsx, lib/windows/app/containers/DeviceSelectorContainer.jsx
Alternative to #180, as suggested by https://github.com/NordicSemiconductor/pc-nrfconnect-core/pull/180#issuecomment-371140677
I'm not a fan of this approach, because I think it increases coupling and the current way of applying class mixins is truly confusing (see https://github.com/NordicSemiconductor/pc-nrfconnect-core/commit/96b8f806381791ed2c2a525b9d8c52cc22a9f568 - both before and after works, which is very weird IMO)
=> Use withHotkey for the device selector

lib/windows/app/actions/firmwareDialogActions.js, lib/windows/app/actions/logActions.js, lib/windows/app/actions/mainMenuActions.js, lib/windows/app/actions/navMenuActions.js, lib/windows/app/actions/serialPortActions.js
Could perhaps consider generating HTML documentation of this at some point if we find it useful.
=> Add jsdoc for all core actions

lib/windows/app/components/AbstractSelector.jsx, lib/windows/app/components/DeviceSelector.jsx, lib/windows/app/components/SerialPortSelector.jsx, lib/windows/app/containers/DeviceSelectorContainer.jsx, lib/windows/app/containers/SerialPortSelectorContainer.js
This takes the "focus device selector on both hotkeys and click" functionality introduced in https://github.com/NordicSemiconductor/pc-nrfconnect-core/pull/174/commits/f5d84d76e34657a3d193aa140b89dc924bff6c86 , and abstracts it away from both the (new) device selector and the (old) serial port selector.
Given that both selectors use exactly the same code for their `focusDropdownButton` method, it makes a lot of sense to have that code in only one place.
This approach aims for the least code changes required for such a refactor.
Note that this pull req targets the `device-selector` branch, not `master`.
=> Abstract the "focus selector on hotkey" logic, minimal approach

lib/util/apps.js, lib/windows/app/components/NavBar.jsx, lib/windows/app/components/Root.jsx, lib/windows/app/containers/RootContainer.js, lib/windows/app/index.js
Adding a `getAppConfig()` function to make it easy to access the `config` object defined by apps.
Currently, this object is only used for defining traits for the device selector, but the plan is that apps can also put firmware configuration in the `config`.
=> Add function for getting the config object from apps

main/config.js
My editor reported that these config values are not in use. Could not find any references with `grep` either, so these are safe to remove.
=> Remove unused config values

apps.json
This will make the programmer app available in nRF Connect. Please verify that the name and description is as expected.
The app repository is still not public, so the "More information" link does not work at the moment. We should perhaps make the repo public before making the app available?
=> Add pc-nrfconnect-programmer to apps.json

README.md
I got an error regarding missing libgconf-2-4 when running electron on a freshly installed Ubuntu 18.04. The latest nRF Connect AppImage seems to work fine without it, as it exists in `/usr/lib` that is mounted by the AppImage:
```
$ find /tmp/.mount_nrfconwjwJPj -name "libgconf*"
/tmp/.mount_nrfconwjwJPj/usr/lib/libgconf-2.so.4
```
So considering this only as a requirement for development.
=> Add libgconf-2-4 as required package for building on Ubuntu

.npmrc, package.json
Upgrading now because Electron v1.6 is not rendering text properly on Ubuntu 18.04. There is a text rendering issue with Electron in combination with freetype v2.8.1, which is installed by default on Ubuntu 18.04. The issue has been fixed in Electron >=v1.7, but it has not been backported to v1.6.
I have done some smoke testing on Ubuntu 16.04 and 18.04, and have not seen any problems yet. More thorough testing on all platforms will be done as part of the v2.4.0 release testing.
=> Upgrade to Electron v1.8

main/registryApi.js, package.json
Over the weekend, npm have made some changes to the way they serve registry data, ref. https://status.npmjs.org/incidents/t3j62lxb7jg3. This seems to have had an effect on nRF Connect, because downloading app tarballs now fail with a 503 status code.
I have done some debugging, and it seems to happen only when accessing the npm registry through the Electron net API. The Node.js https module works as expected, and accessing the registry through a normal web browser also works. We need to investigate a bit more to pinpoint the issue.
Yarn's registry URL still works fine when accessed from nRF Connect. The tarballs are available from there as well, so we can replace registry.npmjs.org with registry.yarnpkg.com, at least as a short-term fix.
=> Use yarn registry for tarball downloads

package.json
The updated dependency has timeout changes and logger/debug fixes.
=> nrf-device-setup dependency updated to 0.2.5

main/config.js
There is a problem with the electron net API and accessing the npm/yarn registries, so we fetch app information from developer.nordicsemi.com until a fix is in place.
This has already been released from the release/2.3 branch and tagged with v2.3.2. Cherry-picking the commit to include it on master as well.
=> Use developer.nordicsemi.com as app registry

package.json
This PR update the version of nrf-device-setup in order to fix dfu bug on MacOS.
=> Update nrf-device-setup version

build/get-nrfjprog.js, build/installer.nsh, package.json
This PR updates the dependency of pc-nrfjprog-js to v1.3.1 which includes nrfjprog 9.7.3.
Download URL has been updated to nrfjprog installer which still needs to be bundled with nRFConnect installer.
=> Include nrfjprog v9.7.3

doc/serial-timeout-troubleshoot.md
Same as https://github.com/NordicSemiconductor/pc-nrfconnect-core/pull/221/commits/011188f87c0a555d1c040b95f5f92f81d298e4cd - only that #221 was merged in without really realizing that change had to be made twice, one per each troubleshooting document.
=> Serial troubleshooting doc: remove another bit about dongle reset-while-plug-in

build/get-nrfjprog.js, build/installer.nsh, package.json
Due to problems discovered with RTT during release testing, we must roll back from nrfjprog v9.7.3 to v9.7.1 for now.
There is a patch release coming up for nrfjprog that should fix the issue, but we will unfortunately not have time to include and test it before the nRF Connect release.
=> Roll back to nrfjprog v9.7.1

main/registryApi.js
When installing apps, the shasum of the downloaded tarball is compared to the shasum from the npm registry. If the shasum verification fails, an error should be displayed to the user.
The error was however not displayed properly (showed up as `undefined`), because this rejection contained a string instead of an error object.
=> Return error object if shasum verification fails

main/registryApi.js
As we are now fetching apps from developer.nordicsemi.com, this workaround is no longer needed.
=> Remove redundant npm registry workaround

lib/windows/launcher/components/UpdateProgressDialog.jsx, lib/windows/launcher/components/__tests__/UpdateProgressDialog-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/UpdateProgressDialog-test.jsx.snap
When clicking Cancel while downloading a new version of nRF Connect, and the download has reached 100%, it does not cancel the operation. The [cancel mechanism in electron-updater](https://github.com/electron-userland/electron-builder/blob/master/docs/auto-update.md#module_electron-updater.AppUpdater+downloadUpdate) is only for cancelling the download operation. Since the download is complete, cancel does not have any effect. Disabling the button in this scenario.
=> Disable Cancel button when download is 100% complete

lib/windows/launcher/actions/autoUpdateActions.js
When starting a download, and cancelling it in the middle of the download process, any subsequent calls to `autoUpdater.downloadUpdate()` failed. This is because the cancellation token from the first download was reused for subsequent downloads. Now creating a new cancellation token for each download.
=> Fix problem with upgrading after having cancelled

index.js, main/apps.js
The `initAppsDirectory` function originally both intitialized the `.nrfconnect-apps` directory and downloaded app information (apps.json and updates.json). The function had error codes to differentiate between errors related to setting up the directory and errors related to downloading of app information.
Later, the fetching of app information was moved out from this function and now happens at the initial render of the launcher window. When doing this, the JSDoc was not updated, so it refers to an error code (`APPS_UPDATE_ERROR`) that does not exist anymore.
Updating the JSDoc and simplifying the code slightly.
=> Minor simplifications of init routine

main/autoUpdate.js, package.json
Previously, the `CancellationToken` was only exposed through electron-builder-http, but with recent versions of electron-updater it is included in the library. This allows us to remove our dependency to electron-builder-http.
I have verified that cancelling the download process during auto update still works as before.
=> Remove electron-builder-http dependency

lib/windows/app/components/LogEntry.jsx, lib/windows/app/components/__tests__/LogViewer-test.jsx, lib/windows/app/components/__tests__/__snapshots__/LogViewer-test.jsx.snap
Also fixed log entry timestamp representation to 3 digits to show milliseconds, since the underlying timestamp object only has that resolution.
=> Add JSX <a> tag around links in log messages

mocks/electronMock.js, package.json
Looks like jest has never documented `genMockFunction()` which has finally been removed, so mock has been updated. Also default transform config doesn't transpile JSX files any more, that has been fixed too.
=> Fix jest default transform and deprecated api calls

lib/windows/app/components/__tests__/__snapshots__/MainMenu-test.jsx.snap, lib/windows/launcher/components/__tests__/__snapshots__/AppLaunchView-test.jsx.snap, mocks/emptyMock.js, package.json
Unfortunately the common jest config doesn't cover the modules directly used by core and configs don't mix, so jest is now called directly from _npm_ rather than by wrapper scripts.
Snapshots are updated too.
=> Fix jest snapshots and mocks

.npmrc, package.json
This PR was created to keep the electron engine up to date with latest stable version 2.0.6.
Fortunately we didn't use any of the braking APIs, so the update is quite straightforward.
Auto-update and some smoke tests has been checked on all platform.
=> Feature/upgrade to electron v2.0

index.js, lib/windows/launcher/actions/appsActions.js, lib/windows/launcher/actions/desktopShortcutActions.js, lib/windows/launcher/actions/settingsActions.js, lib/windows/launcher/components/AppManagementView.jsx, lib/windows/launcher/components/AvailableAppItem.jsx, lib/windows/launcher/components/ConfirmRemoveSourceDialog.jsx, lib/windows/launcher/components/InputLineDialog.jsx, lib/windows/launcher/components/InstalledAppItem.jsx, lib/windows/launcher/components/LaunchableAppItem.jsx, lib/windows/launcher/components/SettingsView.jsx, lib/windows/launcher/components/__tests__/AppManagementView-test.jsx, lib/windows/launcher/components/__tests__/SettingsView-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/AppLaunchView-test.jsx.snap, lib/windows/launcher/components/__tests__/__snapshots__/AppManagementView-test.jsx.snap, lib/windows/launcher/components/__tests__/__snapshots__/SettingsView-test.jsx.snap, lib/windows/launcher/containers/AppManagementContainer.js, lib/windows/launcher/containers/ConfirmRemoveSourceDialog.js, lib/windows/launcher/containers/SettingsContainer.js, lib/windows/launcher/models/index.js, lib/windows/launcher/reducers/settingsReducer.js, main/apps.js, main/config.js, main/fileUtil.js, main/registryApi.js, main/settings.js, main/windows.js, resources/css/launcher.less
This PR adds a new section to the the _SettingsView_ where users can add multiple _apps.json_ URLs for external app sources. nRFConnect creates a new directory `.nrfconnect-apps/external` which will be the root of storing these apps.
There's an extra requirement for any additional _apps.json_, to specify `_source` string member as the source name which will create a new directory under `external`.
New command line argument `source` has been introduced to be able to specify the source which works together with `open-official-app`. This change is also added to desktop shortcuts.
Jest tests and snapshots are updated.
=> Feature multiple sources

lib/windows/app/components/DeviceSelector.jsx, lib/windows/app/components/__tests__/DeviceSelector-test.jsx, lib/windows/app/components/__tests__/__snapshots__/DeviceSelector-test.jsx.snap, resources/css/app.less
With this PR the _DeviceSelector_ component can displays multiple serial ports of a single device, and for better distinction of different devices the board version is also displayed next to the serial number.
=> Support displaying multiple serialports and board version of a device

.npmrc, package.json
Electron versions <2.0.8 fail on various distributions due to glibc 2.28:
* Ubuntu 18.10 beta
* Fedora 29 beta
Some of these distributions will likely patch patch glibc to avoid this
behaviour, but Fedora 29 doesn't seem like it will go this route, and
I'm not yet sure about Ubuntu.
Simply updating electron to 2.0.8+ solves the problem. I chose the most
recent one, but I could go back down to 2.0.8, but I'm not sure why
you'd want to.
=> Update electron to 2.0.11

lib/api/index.js, lib/windows/app/index.js
This PR is due to including nrf-usb and nrf-device-setup into pc-nrfconnect-core so that apps dont need to have duplicated dependencies.
=> Add module support for nrf-usb and nrf-device-setup

README.md
Update information about where to report bugs and feedback. Instead of using *github issues* we would like users to instead use Nordic DevZone for all bug reports and feedback. We believe users will receive faster follow up on DevZone as it backed by tech support and a large community of users. Reports that cannot be handled by tech support directly will as usual be escalated and forwarded to the developers.
=> Update info about bug reporting

lib/windows/app/actions/logActions.js, lib/windows/app/components/LogViewer.jsx, lib/windows/app/components/Root.jsx, lib/windows/app/containers/LogViewerContainer.js, lib/windows/app/containers/RootContainer.js, lib/windows/app/reducers/logReducer.js, resources/css/app.less
This PR introduces a horizontal and a vertical splitter element in the main area which separates the _MainView_ from _LogViewer_ and from _SidePanel_. These elements are draggable which allows the user to resize the latter components.
In order to resize the _LogViewer_, a redux flow had to be added to inform the infinite-log about the new container height.
Apps are not effected by the functionality (so far they all work as expected), however styles might be slightly effected, at least redundant CSS rules need to be deleted in BLE app.
=> Splitter elements allow resizable LogViewer and SidePanel

lib/windows/app/reducers/logReducer.js
This PR limits the number of entries in the _LogViewer_ to 10000, and prepends a user friendly message about the full log which appears always on the first line should the user scroll back.
=> Fix log performance by limiting entries in LogViewer

lib/windows/launcher/components/SettingsView.jsx, resources/css/common/styles.less, resources/css/launcher.less
This PR introduces a button next to the source URL in the Settings tab that copies the URL to the clipboard. The URL's style is also updated to allow selection.
=> Add copy-to-clipboard to source url and make it selectable as well

README.md, apps.json
The PC version of the gateway is no longer maintained and supported.
Please use the Cordova Gateway: https://github.com/nRFCloud/gateway-cordova
=> Remove nRF Connect for Cloud Gateway

azure-pipelines.yml
This PR is due to disabling x64 build. Add it back if it is needed in the future and the electron-updater issue should be fixed at that moment.
=> Disable x64 build

lib/windows/launcher/components/InputLineDialog.jsx, lib/windows/launcher/components/SettingsView.jsx, package.json, resources/css/app.scss
This PR bumps version to 3.0.0+ since bs4 breaks the old apps. Minor styling issue and broken input line is also addressed.
=> Fix minor issues with react-bootstrap 4

resources/app.html
This PR completes #310 by copying the required environment variable to the app's renderer process before the webpacked app is executed.
=> Copy main process env var before loading app

index.js
This fix prevents a crash in nrfjprog when it tries to write its temporary files without correctly setting their paths.
=> Ensure running in a writable directory

main/menu.js
This PR is due to enable devtools on mac.
=> Enable dev tools on macOS

lib/windows/app/actions/deviceActions.js
This PR adds support for apps to define _releaseCurrentDevice_ configuration option to ensure safe reopening of the same device.
=> Add optional promise to wait for when reopening a device

lib/api/logging/__tests__/appTransport-test.js, lib/api/logging/appTransport.js, lib/api/logging/consoleTransport.js, lib/windows/app/components/LogEntry.jsx, lib/windows/app/components/__tests__/LogViewer-test.jsx
This PR fixes the warning about legacy log transport implementation by updating the transports to winston API version 3.
=> Update log transports to winston 3 API

azure-pipelines.yml
This PR should fix Linux builds that are silently broken with missing `libudev.h`.
=> Install libudev-dev on azure for linux

lib/windows/launcher/actions/appsActions.js, lib/windows/launcher/models/index.js, lib/windows/launcher/reducers/__tests__/appsReducer-test.js, lib/windows/launcher/reducers/appsReducer.js, main/apps.js, package.json
This PR adds implementation of downloading release notes from GitHub, which then gets stored by electron-store. The downloaded notes are formatted and assembled to be dispatched and set in application state for further use.
=> Download and store release notes

lib/windows/launcher/actions/appsActions.js, lib/windows/launcher/components/AppManagementView.jsx, lib/windows/launcher/components/__tests__/AppManagementView-test.jsx, lib/windows/launcher/components/__tests__/__snapshots__/AppManagementView-test.jsx.snap, lib/windows/launcher/containers/AppManagementContainer.js, lib/windows/launcher/index.js, lib/windows/launcher/reducers/__tests__/appsReducer-test.js, lib/windows/launcher/reducers/appsReducer.js
This PR fixes multiple requests to the same apps.json during startup and also renders the launcher as soon as local and installed apps are parsed, doesn't wait for the network.
AppManagementView is also cleaned up, unused methods are removed and tests/snapshots updated.
=> Better startup speed and fixed app matching

main/apps.js, main/net.js, main/registryApi.js
In this PR the token based authentication fallback is reverted.
The solution to save github rate limit is to use conditional requests where the ETag header is used to check for updated content.
For this net.downloadTo... functions resolve with an array of [responseData, responseHeaders], so the responseHeader can be used when downloading the release notes.
=> Revert token based GH api calls and use etag match

README.md, apps.json
This PR is due to moving trace collector from Playground to NordicsemiConductor
=> Move Trace Collector to NordicSemiconductor

README.md
Replace developer documentation with link to docs project because the description was moved to [`core_development.md`](https://github.com/NordicSemiconductor/pc-nrfconnect-docs/blob/master/core_development.md) and [`local_app_installation.md`](https://github.com/NordicSemiconductor/pc-nrfconnect-docs/blob/master/local_app_installation.md) in the project [`pc-nrfconnect-docs`](https://github.com/NordicSemiconductor/pc-nrfconnect-docs).
Also: Some heading levels were corrected.
=> Replace developer documentation with link to docs project

azure-pipelines-internal.yml, index.js, lib/store/configureStore.js, main/devtools.js, package.json
This enables the use of the Redux DevTools and eases installing (and removing) the DevTools for Redux and React, which is also described in NordicSemiconductor/pc-nrfconnect-docs#4.
With the Redux DevTools the Redux logger is not needed anymore, so it is removed.
=> Better dev tools

Changelog.md, main/apps.js, main/net.js
This is part of [NCP-2820](https://projecttools.nordicsemi.no/jira/browse/NCP-2820). The whole concept is described there.
With this change the release notes are not fetched from GitHub anymore, instead they are retrieved from developer.nordicsemi.com. E.g. the release notes for the BLE app will be retrieved from http://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/pc-nrfconnect-ble-Changelog.md.
To make the launch faster and spare users with a slow connection some bandwidth, the launcher uses [ETags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag), to retrieve the changelog only if it has changed.
I already uploaded changelogs manually for each app to developer.nordicsemi.com, so they are already there. This is useful for testing now and also that we are able to use …
=> Changelog as release notes

src/main/devtools.js
This fixes [NCP-2844](https://projecttools.nordicsemi.no/jira/browse/NCP-2844), a bug which was introduced in bada7bfc by always depending on
electron-devtools-installer, even though it is only provided when
installing the dev dependencies, so it breaks in production.
So instead we now wrap a try-catch around the `require` and provide the
functionality to install and remove devtools only if that dependency
can be resolved.
Actually, we could always provide the functionality to _remove_ the
devtools, but that would be a strange imbalance.
This PR does not add an entry to the changelog, because we had no 
release with this error.
=> Fix: Launcher could not start in production

package.json, src/legacy/app/actions/deviceActions.js
This PR is to avoid deselecting device when error occurs during device setup. It allows apps to use custom device even though there is no firmware provided for such devices in the apps.
=> Allow custom device

package.json, src/launcher/actions/appsActions.js, src/launcher/actions/autoUpdateActions.js, src/launcher/actions/settingsActions.js, src/launcher/containers/SettingsContainer.js, src/launcher/index.js, src/main/apps.js, src/main/net.js
This fixes [NCP-2674](https://projecttools.nordicsemi.no/jira/browse/NCP-2674).
When the launchers gets a 404 for a source, it now displays this dialog, which explains the situation better and lets users directly remove the broken source:
For other error (e.g. when the user is offline), the old error message is still shown:
As you can see, even the latter case is slightly enhanced, because the URLs are now clickable.
The main change is done in the first two commits, the third was only needed to break a mostly harmless import cycle.
=> Enhance removed sources handling

src/legacy/app/components/__tests__/LogViewer-test.jsx
react-infinity was removed in 9f7a4b08b0, but this mock was forgotten.
=> Remove outdated mock

apps.json
This PR is to add toolchain manager to apps.json
=> Add toolchain manager to apps.json

package.json, serialport-prebuild-installrc, src/app/module-loader.js, src/legacy/api/jlink/index.js, src/legacy/app/actions/serialPortActions.js, src/legacy/app/components/DeviceSelector.jsx, src/legacy/app/components/FirmwareDialog.jsx, src/legacy/app/components/SerialPortSelector.jsx, src/legacy/app/components/__tests__/DeviceSelector-test.jsx, src/legacy/app/components/__tests__/FirmwareDialog-test.jsx, src/legacy/app/components/__tests__/SerialPortSelector-test.jsx, src/legacy/app/reducers/__tests__/firmwareDialogReducer-test.js, src/legacy/app/reducers/__tests__/serialPortReducer-test.js, src/legacy/app/reducers/serialPortReducer.js, src/legacy/portPath.js
Part of [NCP-2996](https://projecttools.nordicsemi.no/jira/browse/NCP-2996).
The main change of the upgraded nrf-device-setup dependency is that it brings in serialport 8, from which two changes are especially relevant for us:
- `SerialPort.list` does not take a callback anymore but instead you now always have to use the returned Promise.
- The property `comName` on ports is deprecated (though still supported) and one should use the property `path` instead.
=> Upgrade serialport

src/launcher/components/AppManagementFilter.jsx
This PR moves the Filter and Search components to the left, the Update All Apps button to the right side.
=> Move Filter and Search to the left side

src/launcher/components/AppIcon.jsx, src/launcher/components/__tests__/__snapshots__/AppManagementView-test.jsx.snap, test-e2e/launcher/engineVersionCheck.test.js
4af1267993 introduced a regression: Now all apps that are available online (but not yet installed) did show a warning about a missing engine version.
=> Fix: No engine warning for available apps

Changelog.md, package.json, src/main/apps.js, src/main/fileUtil.js
Fixes the bug [NCP-3115](https://projecttools.nordicsemi.no/jira/browse/NCP-3115).
When users press “Update all apps” sometimes an error message “Unable to load apps” was shown (even though it worked correctly). 
This was caused by a race condition: When one app was completely upgraded it reloaded the state of all apps but another one was possible in the middle of being upgraded, which could lead to it's app folder being transiently in an inconsistent state. E.g. while deleting the old version, the `package.json` was already gone but the folder still existed.
To fix this, when removing the old version of the app, the app folder is first moved to different, temporary folder and the contents are removed there. When installing the new version it is done the other way around: The downloaded …
=> Fix “Update all apps”

Changelog.md, package.json
This PR updated pc-ble-driver-js to 2.7.2, for changes see: https://github.com/NordicSemiconductor/pc-ble-driver-js/releases/tag/v2.7.2
=> Update pc-ble-driver-js to 2.7.2

.huskyrc.json
Remember that in a case of emergency you can do `git push --no-verify`
if you need to push even though tests might fail.
=> Automatically run tests before push

src/main/net.js
If proxy authentication is required, electron will show error dialog as described in https://github.com/electron/electron/issues/24948. This is a workaround until the issue has been fixed.
=> Added workaround to prevent errors when proxy authentication is required

src/legacy/app/components/LogEntry.jsx
Handle cases where the error message passed to the component is an object instead of a string as we expect.
=> Fix when error message is object instead of string

resources/css/app.scss
Issue with chromium, explained in more detailed here https://bugs.chromium.org/p/chromium/issues/detail?id=927066. Particularly comment #50 explains the reason this fix works.
=> Set min-height: 0 on main window layout to prevent double scrollbar issue

Changelog-dev.md, src/app/module-loader.js
This PR patches electron's dialog api for apps which are not yet updated.
Should an app use _showSaveDialog()_ or _showOpenDialog()_ must expect a Promise return.
This will be the case as soon as the app updates required nrfconnect engine version to 3.6+ in package.json, until that the app will see a patched api which should behave as in the old api.
=> Temporary dialog API patch

resources/css/launcher.scss
The arrows in the dropdown buttons were a wee bit misaligned; this PR corrects that.
Before:
After:
=> Fix dropdown toggle alignment

resources/launcher-dev.html, webpack.config.js
With this one can start the compilation e.g. with
PORT=5432 npm run dev
and the app with
PORT=5432 npm run app
This will also require a change to `shared`, where https://github.com/NordicSemiconductor/pc-nrfconnect-shared/blob/6d887d0e1c6dd1744f6ed3f2c6c26efc95551180/scripts/build.js#L85 has to be replaced by 
```js
const port = process.env.PORT || 5004;
```
=> Make port of the hot reload server configurable

Changelog-dev.md, Changelog.md, src/launcher/actions/appsActions.js, src/launcher/reducers/appsReducer.js
After updating an app the others were not showing release notes anymore.
This was caused by this: After we update an app, we reload the data for all online available apps (the function is called `getOfficialApps` but it really loads from all sources). This causes existing data about the apps to be wiped, including the release notes. But as an optimisation we reload only the release notes about the just updated app, so the other apps are then left without release notes.
This fix does not wipe the existing data about all apps, only data about the just updated app is overwritten with the online data about it, thus the release notes from other apps are not removed anymore.
This is a bit of a quick fix. I think there are better ways to solve it but they would take more changes which do not …
=> Fix: Missing release notes after app update

Changelog.md, src/main/windows.js
Before only the version of the launcher was shown.
Checked that this also works in old app: 
as well as in the PPK app which does modify it's title:
=> Show app version in title bar

Changelog-dev.md
Because it does not describe a change that is visible to the app
developers.
=> Remove changelog entry

Changelog-dev.md, src/legacy/portPath.js
This provides at least a step in the direction of fixing [NCP-3537](https://projecttools.nordicsemi.no/jira/browse/NCP-3537). Currently `serialport` is undefined, which causes the app to crash. But I don't know if this prevents any issues further in the process since I am unable to reproduce this issue locally.
=> Handle undefined serialport

package-lock.json, package.json, src/launcher/components/ErrorBoundaryLauncher.jsx, src/launcher/components/Root.jsx, src/launcher/containers/AppManagementContainer.js
This PR implements [https://trello.com/c/Ktagc7cB/74-add-error-boundaries-to-launcher-itself](https://trello.com/c/Ktagc7cB/74-add-error-boundaries-to-launcher-itself).
Updates to `shared` [(v4.23.1)](https://github.com/NordicSemiconductor/pc-nrfconnect-shared/commit/a182e04e81de1cd512abfd7e458a9c9a72a9d8a0) now allows for overriding factory reset and GA event report sending when component is initialized, so add a wrapper which implements this functionality.
Turns out that just deleting `settings.json` and reloading the app didn't work properly as the file was just re-created with the problematic values. So instead we go for a softer factory reset where we just clear the `filter`, `show` and `source` state.
We also use the GA reporting functionality provided by the launcher itself instead …
=> Add Error Boundary to the launcher itself.

Changelog.md, src/launcher/actions/autoUpdateActions.js, src/main/apps.js
The error message when an app.json for a source is missing on the server did not show up, because `isResourceNotFound` was called through a `remote.require`, which strangly lead to the error object not being filled correctly. Now `isResourceNotFound` is called in the main thread and thus it works.
You can reproduce this by putting a source in `~/.nrfconnect-apps/external/sources.json` with an URL that is not found. Then you get this:
=> Fix: Tailored error for missing source file

src/launcher/actions/appsActions.js, src/launcher/actions/usageDataActions.js, src/main/apps.js
This commit contains three core improvements:
- Replace `Promise.all` with `Promise.allSettled` to let the user select
among the working apps even if one has failed.
- Send event to GA to know how frequently this occurs. If it is a common
occurence we might consider improving the robustness of the installation
routine.
- Add `Recover` button that attempts to remove the corrupted directories
=> Improve user experience when installed files are corrupted.

Changelog-dev.md, Changelog.md, src/main/config.js, src/main/index.js, src/main/setUserDataDir.js
Fixes #551 by enabling users to set the [user data directory](https://www.electronjs.org/docs/api/app#appgetpathname) through command line switch `--user-data-dir` or environment variable `NRF_USER_DATA_DIR`. 
Also updates `Changelog.md` and `Changelog-dev.md` according to our latest discussions.
=> Set user data dir

src/launcher/components/ReleaseNotesDialogView.jsx, src/launcher/containers/ReleaseNotesDialogContainer.js
Trello: [Wrong button in Release notes for uninstalled apps](https://trello.com/c/aBGhRWQ0/193-wrong-button-in-release-notes-for-uninstalled-apps).
For uninstalled apps there was a wrong “Update to latest version” button in the release notes dialog. This changes the wording to “Install”.
=> Fix wrong button in release notes

resources/css/launcher.scss, src/launcher/components/AboutView.jsx, src/launcher/components/Root.jsx, src/launcher/components/SettingsView.jsx, src/launcher/components/__tests__/__snapshots__/SettingsView-test.jsx.snap
Trello task: https://trello.com/c/jqpJN6MA/226-add-license-to-launcher
changed from
=> Add lincense to launcher

Changelog.md, src/legacy/app/actions/legacyAppDialogActions.ts, src/legacy/app/components/LegacyAppDialog.jsx, src/legacy/app/components/Root.jsx, src/legacy/app/containers/LegacyAppDialogContainer.js, src/legacy/app/legacyAppWarning.ts, src/legacy/app/reducers/legacyAppDialogReducer.ts, src/legacy/components/ConfirmationDialog.jsx, src/legacy/legacyRenderer.jsx
Since we would like to deprecate the old architecture eventually, this change displays this warning when users launch an app that still uses the old architecture:
The warning also points app developers to https://nordicsemiconductor.github.io/pc-nrfconnect-docs/migrating_apps, so they know how to update their apps.
Besides that users can permanently dismiss the warning per app, our own apps where we are aware that we still have to update them are also excluded: https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/blob/bc92cfbccf57f27eebc186b0037ade54d25d57be/src/legacy/app/legacyAppWarning.ts#L53-L60
One way of testing this feature is by adding the Actinus source https://cdn.actini.us/nrf-apps/apps.json to the launcher and then installing and launching their programmer.
=> Show a warning when launcher apps using the old architecture

azure-pipelines.yml
Since shared 5.0.0 we need at least Node.js 14. Without this, the builds currently fail.
=> Fix: Use correct node version in automated build

package.json, src/main/browser.js, src/main/windows.js
This PR hopefully fixes [this issue](https://trello.com/c/GTmCpCug/275-launcher-freezes-on-startup-until-window-is-moved).
A bug in newer versions of Electron seems to cause the launcher to hang indefinitely on start-up. This issue refers to something similar: [https://github.com/electron/electron/issues/24329](https://github.com/electron/electron/issues/24329)
In this issue the reporter mentions that replacing `loadURL` with `loadFile` avoids the problem. So we'll try this fix in lack of something better.
The reason I write hopefully fix is that since this issue didn't occur on every app start, we cannot be 100% confident that this fixes the problem. I have started the apps many many times to test and never encountered the issue with this fix implemented, so it seems to be good.
Another …
=> Replace `loadURL` with `loadFile` when loading Launcher HTML file

Changelog.md, src/launcher/components/AppManagementFilter.jsx
Fixes an issue with shortcuts not persisting after opening the filtering
menu. This commit fixes the issue by using a reference to the target
component to be focused when pressing the key binding.
=> Fix: search field shortcuts persists

azure-pipelines.yml
To fix the notarisation problem in `master` the same way we did in `release/3.9`.
=> Fix macOS build

Changelog.md, src/launcher/components/Root.jsx, src/launcher/index.js
Fixes https://trello.com/c/cSRL9Y9V/292-macos-remove-element-focus-on-some-launches
As described in the Trello card, an unwanted focus ring was shown sometimes on macOS.
The fix was not quite as easy as just adding a `document.activeElement.blur()` because the element was not already focussed right after the initial render but a moment later. And it is not always focussed, so after 50 milliseconds we stop waiting for it.
=> Fix initial focus on macOS

Changelog-dev.md, Changelog.md, package-lock.json, package.json
Because the bug was not released, we do not need to note it in the changelog.
The upgrade to shared 5.12.2 also fixes two other minor aspects but I think barely anyone will notice the added margin on macOS, so I did not copy that into the changelog.
=> Fix: Crash when opening device details in device lister

Changelog.md
Also fixed it in [the 3.9.2 release notes](https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/releases/tag/v3.9.2).
=> Fix: Small spelling mistake

Changelog.md, doc/proxy-settings.md, doc/serial-timeout-troubleshoot.md, doc/win32-usb-troubleshoot.md, src/launcher/actions/autoUpdateActions.js, src/launcher/components/ProxyErrorDialog.jsx, src/launcher/components/UpdateAvailableDialog.jsx, src/launcher/components/UpdateProgressDialog.jsx, src/launcher/components/UsageDataDialog.jsx, src/launcher/components/__tests__/__snapshots__/AppManagementView-test.jsx.snap, src/launcher/components/__tests__/__snapshots__/UpdateProgressDialog-test.jsx.snap, src/launcher/util/checkAppCompatibility.ts, src/legacy/app/actions/mainMenuActions.js, src/legacy/app/components/__tests__/DeviceSelector-test.jsx, src/legacy/components/Logo.jsx, src/main/config.js, src/main/index.js, test-e2e/launcher/engineVersionCheck.test.js
Enhanced the messages shown when an app is not compatible with the launcher. E.g. when the versions of shared did not match, this was before the dialog:
The new dialog looks like this:
Notable changes:
- Call it "nRF Connect for Desktop" not just "nRF Connect".
- Users usually have no clue, what is meant by "shared", so be a bit more verbatim and call it "the internal pc-nrfconnect-shared library".
- When an app needs a more recent version of shared, indicate also that updating nRF Connect for Desktop might help.
I consider none of these changes to be relevant enough, to also mention them in the changelog.
In 9555c95f9bc75900ed9f43827ebd89879b5d9109 also all other usages of the short "nRF Connect" was changed to "nRF Connect for Desktop", which should help to not confuse it with other nRF …
=> Enhance incompatibility messages

webpack.config.js
We already provided the source maps before but did not link them. With this small change the source map is also used in production.
Before this, when opening the sources in the developer tools, there were only the compiled sources: ![image](https://user-images.githubusercontent.com/260705/151826702-4f5caa64-181e-4176-ad67-c0e7235e0096.png)
After this, there is now an additional `webpack://`-entry containing the raw sources (which can also be opened using the Ctrl/Cmd-P shortcut):
=> Use source map in production

package-lock.json, package.json
The new version of `electron-store` removes the use of `electron.remote`, which is a plus.
Because we use `electron-store` also from the main process (in `src/main/apps.js`), there is nothing further we have to change. If we ever remove that usage from the main process in the future, we would have to add a call to `Store.initRenderer()` in the main process, as described in the release notes of v7: https://github.com/sindresorhus/electron-store/releases/tag/v7.0.0
=> Upgrade electron-store

babel.config.js, webpack.config.js
This basically replicates the babel setup from shared, but removes a single plugin "add-module-exports plugin".
This plugin changes what's exported from some modules and causes errors where pre-built dependencies would try to resolve default properties on commonjs-modules which were converted to esm-style export with this package.
It is quite possible that this should just be removed in shared all-together. But I think it's best to rather remove it from the launcher to get launcher in a working state, as it will take some time to test all apps built by shared with this change as well.
=> Remove add-module-exports plugin

Changelog.md, package.json, src/main/config.js
The app list is not loaded from GitHub any longer but from developer.nordicsemi.com, which should be easier to reach from China.
This has the consequence though, that we now have to keep https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/apps.json in sync with https://raw.githubusercontent.com/NordicSemiconductor/pc-nrfconnect-launcher/master/apps.json. The latter still needs to be maintained as long as we want to also support older versions of nRF Connect for Desktop.
=> Enhance reliability in China

Changelog.md, package-lock.json, package.json, src/launcher/models/index.js, src/launcher/reducers/appsReducer.js, src/launcher/reducers/autoUpdateReducer.js, src/launcher/reducers/proxyReducer.js, src/launcher/reducers/releaseNotesDialogReducer.js, src/launcher/reducers/settingsReducer.js, src/main/net.js, test-e2e/assertions.ts, test-e2e/launchFirstApp.ts
This makes the launcher ready for release testing 3.11.1.
The update to 6.1.0 makes apps (which not bundle `shared` 6.0.*) display an Audio Kit by its name. It also speeds up app launcher (at least under Windows, not yet testet on other platforms).
=> Update `shared` to 6.1.0

package-lock.json, package.json
Because we now use `winston` in `src/main/autoUpdate.js` (which we do not bundle), we must now include `winston` as a normal dependency. Otherwise we get an error when launching the built executable.
=> Add missing winston dependency

package-lock.json, package.json, src/app/initApp.js
As described in NordicSemiconductor/pc-nrfconnect-shared#364, calling `logger.addFileTransport` must be removed from the launcher because it makes logging fail in apps that bundle shared.
=> Fix: Logging with bundled apps

package-lock.json, package.json
Updates `nrf-device-lib-js` to 0.4.11.
=> Fix: BLE app problem on macOS

build/installer.nsh
During installation (on windows), there will be prompts to install other software machine-wide (jlink and nrf device lib driver). This causes an issue when users have focused away from the installer, causing the admin-elevation prompts to "hide" on the start-menu, instead of popping up for user consent. Bringing the installer into focus will mitigate this, even though it seems it doesn't always work (possible race condition between bringing window to focus and starting installation.
=> Attempt to bring window to front.

package-lock.json
Even though the package `cli-truncate` is required while packaging on macOS it got accidentally removed. Seems like an error by npm. An `npm install` fixed the `package-lock.json`.
=> Fix: packaging on macOS

src/ipc/appDetails.ts, src/ipc/openWindow.ts, src/ipc/preventSleep.ts, src/launcher/actions/appsActions.js, src/main/index.ts, src/main/registerIpcHandler.ts, src/main/windows.ts
- Move the remaining IPC code into `src/ipc/`.
- Extract the whole code to register all IPC handlers from `src/main/index.ts` into its own file `src/main/registerIpcHandler.ts`.
=> Cleanup: convert remaining IPC code

src/launcher/actions/appsActions.js, src/launcher/actions/autoUpdateActions.js, src/launcher/index.js, src/launcher/util/registerIpcHandler.js, src/main/configureElectronApp.ts, src/main/index.ts, src/main/menu.ts, src/main/storeExecutablePath.ts
Extract code out of `main/index.ts` and `launcher/index.js` to make the entry points more concise.
=> Cleanup entry points

src/app/initApp.js, src/app/module-loader.js
When all apps are upgraded to shared version 6 (bundled shared), this will remove shared from the bundle that initializes the apps. Causing a big decrease in bundle size and skipping unnecessary code running today when an app is loaded.
The only known remaining app on < 6 is ppk, which will release with an upgraded shared soon hopefully.
=> Remove shared from app bundle

src/launcher/features/apps/App/ShowReleaseNotes.tsx
The button to display the release notes of an app was never shown.
This was caused by the previous split of the `App` component. So it was never released and also must not be mentioned in the changelog.
=> Fix: Show release notes button

Changelog.md, src/launcher/features/apps/App/AppProgress.tsx, src/launcher/features/apps/App/CreateShortcut.tsx, src/launcher/features/apps/App/InstallApp.tsx, src/launcher/features/apps/App/OpenApp.tsx, src/launcher/features/apps/App/UninstallApp.tsx, src/launcher/features/apps/App/UpdateApp.tsx, src/launcher/features/apps/appsSlice.ts
Before, all apps were locked (could not be installed, removed, upgraded, or launched) while any app was installed, removed, or upgraded. Now only the app that is actually changed is also locked for the duration of that operation.
The users can now still interact with the other apps, e.g. install two apps at the same time or open one while another is being installed.
So, this was how could look before: 
https://user-images.githubusercontent.com/260705/196710111-db58ce33-12a5-4d41-aecf-83c85fb12e0c.mov
This is how it can be now: 
https://user-images.githubusercontent.com/260705/196710231-eeeaefdd-8d14-4389-94ad-8e8806c94bb1.mov
=> Feature: Per app locking

src/ipc/apps.ts, src/launcher/features/apps/appsEffects.ts, src/launcher/features/apps/appsSlice.ts, src/launcher/util/DropZoneForLocalApps.test.tsx, src/launcher/util/DropZoneForLocalApps.tsx, src/main/apps.ts, src/main/registerIpcHandler.ts
A bunch of enhancement over the basic implementation:
- Ignore when dropping anything else than files, e.g. text
- Allow dropping multiple files
- Show a helpful error message when a dropped file cannot be installed (e.g. because its filename is not as expected or because it cannot be unpacked as a TGZ archive)
- When dropping a file for which an app is already installed, ask the users whether they want to overwrite the latter or cancel.
Part of https://trello.com/c/AvcUcoIb
=> Enhance drag & drop to install local apps

src/main/apps.ts
If an app package is dropped where the filename and internal app name do not match, then do not install it:
https://user-images.githubusercontent.com/260705/199466255-01922ecc-cfd1-4515-b88a-cac8c633b63a.mov
If a local app directory exists where the internal app name does not match the directory name, then hide the app:
https://user-images.githubusercontent.com/260705/199466425-0fb51b68-cfd9-4f29-b67c-d72ae0a0021d.mov
Part of https://trello.com/c/AvcUcoIb
=> Detect wrong app names for local apps

Changelog.md, jest.config.js, package-lock.json, package.json, scripts/esbuild.js, src/ipc/README.md, src/main/log.ts, src/main/registerIpcHandler.ts, src/main/serialport.test.ts, src/main/serialport.ts, src/main/utils/map.ts, src/test/setupMocks.js
- Updated serialport from `serialport.io` from v8 to v10
- Implemented `serialport.ts` which keeps track of serialports and subscribing renderer processes
- Implemented IPC communication between main process and renderer processes in order for the renderer process to ask for serialport communication through the main process. Implementation of a SerialPort wrapper may be found in https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/429
edit: changed https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/423 -> new PR https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/429
=> Serialport main process

package-lock.json, package.json
`cli-truncate` _should_ be automatically installed, because it is a transitive dependency of `iconv-corefoundation`. But it keeps being removed from `package-lock.json` and I have no idea why. And without `cli-truncate` building the release artefacts on macOS fails. So I add it as an explicit dependency now. 🤷
=> Fix build on macOS

package-lock.json, package.json, src/app/module-loader.js
This is needed because electron-builder will ignore the transitive dependency on serialport from shared when creating the app.
=> Add serialport dependency

Changelog.md, src/ipc/apps.ts, src/launcher/util/appCompatibilityWarning.test.ts, src/launcher/util/appCompatibilityWarning.ts, src/launcher/util/minimalRequiredAppVersions.ts
Keep in `minimalRequiredAppVersions.ts` a list of apps where we know, that the current version of the launcher requires at least a certain app version. 
If the installed app is older than that version, then warn about this. A warning is shown as an orange exclamation mark over the app icon and when hovering over that, a pop up is shown:
If the users launch the app nonetheless, an additional warning is shown (comment to testers: This warning is not shown if you run the launcher from source, you need to build an executable for this, e.g. by running `npm run pack`):
If an app version that is recent enough exists, then the users are informed in the latter dialog that they should upgrade:
~Still missing are appropriate versions for all apps in `minimalRequiredAppVersions.ts`.~
=> Check for minimal app versions

src/launcher/features/filter/AppFilterBar.tsx
The Filter button in the launcher was sometimes stuck in an “active” state. To reproduce:
- Click in Search field
- Hit tab to focus the Filter button
- Hit space twice to open and close the Filter Dropdown
- Hit tab to focus the Search field again
Expected: A Filter button rendered as inactive (white background)
Actual: A Filter button rendered as active (dark grey background)
https://user-images.githubusercontent.com/260705/212696406-71c4f39c-5584-49d5-bb1c-dd516f990bf5.mov
=> Fix: Stuck state of Filter button

src/launcher/util/minimalRequiredAppVersions.ts
Because the version 2.1.0 does not work with launcher 4.0.0.
=> Set a minimal version for GSA

src/launcher/features/localAppInstall/dropZoneInfo.module.scss
- Open a dropdown by clicking on the triangle button and leave it open without selecting anything
- Drag a file over the launcher window while the menu is open
Expected: Show dropzone info in front of all other elements Actual: The dropdown appeared in front of the dropzone info
Cause: Bootstrap uses z-indices around 1000.
https://getbootstrap.com/docs/4.0/layout/overview/#z-index
Fix: Use a z-index of 2000 for the overlay, so it appears in front of all bootstap components.
Before:
Now:
=> Fix: Dropdown appeared in front of dropzone info

package.json, src/main/browser.ts
<a target="_blank" used to open external browser, but now opened in an electron window as well. This fix rectifies that. Links still open in an external browser.
=> Don't open electron browser when clicking anchor tags

src/main/apps.ts
If an updates.json file was corrupt (e.g. just an empty file) the launcher was:
- Not showing any downloadable apps
- Not creating a correct updates.json file
- Not showing any sources besides official and local
=> Fix: Handle corrupt updates.json gracefully

src/launcher/features/apps/appsEffects.ts
If there was a more recent version of an app available on the server but the launcher did not yet know about it (e.g. because “Check for updates at startup” is disabled), the launcher got confused when installing the app.
- Version 1 of an app is locally installed
- Version 2 of an app is available on the server
- Locally we do _not_ have the version yet, that version 2 is available (e.g. because “Check for updates at startup” is disabled)
- Uninstall version 1 of the app (after this, the launcher still shows version 1 as being available))
- Install the app again
- Version 1 of the app is installed
- No available update is shown (until the server is checked for an update, e.g. the launcher is restarted or “Check for updates” is clicked in the settings)
- Version 2 of the app is installed …
=> Fix: Install too recent version

src/main/fileUtil.ts
Some have a `.vscode` directory in the directory of the local apps and    we want to ignore that.
=> Fix: Ignore hidden dirs in local apps dir

src/main/fileUtil.ts
The fix in #779 made symlinked local apps not show up anymore. This fixes this again.
=> Fix: Show symlinked local apps again

src/launcher/features/sources/sourcesEffects.ts, src/main/apps.ts, src/main/registryApi.ts, src/main/sources.ts
This fixes two bugs around adding sources:
- Added source should be directly visible.
- Installing apps from a freshly added source failed.
When adding a source, it was initially hidden by the filter. But when you add a source, you usually also want to work with it right away, e.g. install an app from it. So it is better to have it initially visible.
Steps to reproduce:
- Remove the “Test” source (if you have it)
- Add the “Test” source  https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/test/apps.json
- Go to the apps list and search, e.g. for the Getting Started Assistant
Expected result:
- It is shown with the installable version v2.1.1 by the source name  “Test”
- Clicking on “Install” installs it
Actual result:
- No version for the app by the source name “Test”
- Clicking on …
=> Fix: Adding sources

src/ipc/apps.ts, src/launcher/features/apps/App/App.tsx, src/launcher/features/apps/App/InstallApp.tsx, src/launcher/features/apps/App/ShowReleaseNotes.tsx, src/launcher/features/apps/App/UpdateApp.tsx, src/launcher/features/apps/appsSlice.ts, src/launcher/features/filter/UpdateAllApps.tsx, src/launcher/features/releaseNotes/ReleaseNotesDialog.tsx, src/launcher/util/appCompatibilityWarning.ts, src/main/apps.ts
Handle the case, when an app was once downloadable and installed by users but is now removed from the server.
Until now, the app then just disappeared from the launcher, even though it was still installed in the filesystem.
Now, it stays as an installed app, is marked as “not available for download any more”, and can still be opened as normal. After clicking on “Uninstall” it completely disappears.
Implements https://trello.com/c/ugc49yNz/894-fix-keep-installed-apps-visible-when-removed-on-server
- Add the “Test” source https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/test/apps.json and the “Release Test” source https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/release-test/apps.json if you do not have it already.
- Install the “Getting Started Assistant” from the …
=> Support withdrawn apps

src/ipc/config.ts, src/ipc/openWindow.ts, src/main/browser.ts, src/main/config.ts, src/main/configureElectronApp.ts, src/main/registerIpcHandler.ts, src/main/windows.ts
Extend the IPC call with channel `open:app`, in order to also provide a device and serial port to open automatically when the app is opened. One use case is Cellular Monitor, where we want to open Serial Terminal, and to avoid having to setup the device, and the serial port, we want to simply open the Terminal and have it ready to read and write to the correct serial port.
- The PR bumps several versions of pc-nrfconnect-shared, from `v6.18.1` to `v13`
- The `lockFileVersion` is now `v3` (package-lock.json). The npm version used was `v9.5.0`, and the related node version was `v18.14.2`. The motivation to bump npm version was that the npm install did not work on pc-nrfconnect-shared, and the only reason I found was that the git install was incompatible with the version of npm, and bumping …
=> Extend `open:app` IPC channel

package-lock.json, package.json, src/ipc/apps.ts
Implement https://trello.com/c/i7TRarLY: For officially released apps, the SHA must never changed because we never re-release the same version. But for test releases we do that. And until now, that meant that you do not get a notification that a test release has changed. But now the SHA will change when a new test release is published, which makes it easier for people testing releases.
To test this, you can e.g. go to an app, build and publish it once to the test source source with this:
```
npm run build:prod && npm  run  nordic-publish -- -s test
```
Install the app in the launcher.
Then append a newline to `package.json` and build and publish it again:
```
echo >> package.json && npm run build:prod && npm  run  nordic-publish -- -s test
```
Restart the launcher and it will show an …
=> Offer update for re-released apps

package-lock.json, package.json, src/app/index.jsx
This is done through filewatchers watching the bundle.js and bundle.css. 
A change to the bundle.js remounts the `App` component. 
A change in the bundle.css simply updates the stylesheet node with a new querystring to avoid reusing cached versions.
=> feat: add hot-reloading for apps

src/app/index.jsx
If you want to disable it, you can set the environment variable
`DISABLE_APP_RELOADING` to something during runtime, e.g. by running the
launcher like this:
DISABLE_APP_RELOADING=1 npm run app
=> Enable disabling automatic app reloading

src/app/device-lib-js.ts
With `id as unknown as number` we have to remember to remove it when it is fixed upstream. With `@ts-expect-error` the type checker gives us an error as soon as it is fixed upstream and we have to remove the override.
=> Enhance override for wrong signature

src/launcher/features/apps/InstallOtherVersionDialog.tsx
When selecting an older version of an app to install: Show latest app versions on top.
=> Show latest app versions on top

package-lock.json, package.json, src/launcher/features/apps/App/InstallOtherVersion.tsx, src/launcher/features/apps/InstallOtherVersionDialog.tsx, src/launcher/features/apps/installOtherVersionDialog.module.scss, src/launcher/features/launcherUpdate/UpdateProgressDialog.tsx, src/launcher/features/launcherUpdate/__snapshots__/UpdateAvailableDialog.test.tsx.snap, src/launcher/features/launcherUpdate/__snapshots__/UpdateProgressDialog.test.tsx.snap, src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap, src/launcher/features/sources/__snapshots__/ConfirmRemoveSourceDialog.test.tsx.snap
When there were too many versions to display, the whole window showed a scrollbar, which would scroll away the dialog.
Now, if there are more than 8 versions available, a scrollbar will be shown in the dropdown instead.
This also changes the colour of the dropdown to dark, because I found no easy and not too dirty way to change this.
This also changes the font size of the items in the dropdown list (before it was bigger, now it is 14px, just like the surrounding text).
https://user-images.githubusercontent.com/260705/234587754-99d2c39d-e44e-4740-993e-03e6123bed65.mov
Only if multiple versions exist the button to install other versions should be shown. When only a single version was released, we do not need to show the button.
Occasionally it can also happen, that no versions at all are …
=> Enhance installing other versions

package.json, src/launcher/features/apps/InstallOtherVersionDialog.tsx, src/launcher/features/apps/installOtherVersionDialog.module.scss
Just having a simple div was already enough to avert the `width: 100%` of the Dropdown.
The previous CSS was even illegal because of the quotes.
=> Fix: Remove unneeded class

package-lock.json, package.json, src/ipc/appDetails.ts, src/launcher/features/apps/installOtherVersionDialog.module.scss, src/main/windows.ts
When installing other app versions, the dropdown for the version list is enhanced in several regards:
- If it has scrollbars, they are working correctly (one can click on them or drag the slider), before clicking on them closed the dropdown.
- The scrollbars are styled consistently with the rest of the UI
- The items are now centred vertically
Also fixed a regression: Apps showed the app path as “undefined” in their log.
=> Enhance installing other versions … again

src/launcher/features/settings/Settings.tsx
The URLs for sources changes in the 4.1 release, e.g. from https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/crasher/apps.json to https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/crasher/source.json (notice the different filename at the end).
The old URL (with `apps.json` at the end) will continue to work for now. Users of 4.0 and before need the old URLs anyhow, as these versions cannot understand the new files.
So, for now we prefer that people continue to distribute the old URLs, since they work with both old and new releases.
For this, the “Copy URL” function now also copies the old URL.
=> Copy old source URL

Changelog.md, src/main/apps/sources.ts
When nRF Connect for Desktop was never installed on a computer before, a misleading error message (Unable to retrieve the official source from …) was shown and it was impossible to install any apps.
=> Fix: Error on fresh install

Changelog.minor.md, package-lock.json, package.json, src/main/apps/apps.ts
Fixes https://trello.com/c/sC0xkJct.
To reproduce:
1. Remove the folder ~/.nrfconnect-apps (to start out with a clean, controlled state)
2. Run the launcher 4.1.1. With it install the Programmer app and quit it.
3. Run the launcher 4.0.1. With it uninstall Programmer and quit it.
4. Run the launcher 4.1.1.
Now the launcher showed the Programmer as seemingly installed again but launching or uninstalling it did not work.
=> Fix: Wrong app state when downgrading launcher

Changelog.minor.md, package-lock.json, package.json, src/ipc/apps.ts, src/ipc/serialport.ts, src/launcher/features/filter/filterSlice.ts, src/launcher/features/sources/sourcesEffects.ts, src/main/apps/apps.ts, src/main/apps/sources.ts
For  https://trello.com/c/r6e7BZHe:
When a source failed to load, the error message “Unable to retrieve …” makes an assumption about the possible cause (“… usually caused by a missing internet connection”) but error reports from users showed us that we are not sure about this and it might also be caused by other things. E.g. in https://trello.com/c/RQnktqXb it was caused by something else.
To understand cases like these better, it is helpful to also get more technical details, e.g. the exception thrown. But we don’t want to display raw exceptions in all these cases, because that would not be user-friendly. So now we display a “Show technical details” button, which then reveals the text of the exception.
An example of the changed error dialog can be seen in …
=> Enhance error dialog

Changelog.md, resources/app.html, src/launcher/features/apps/App/AppIcon.tsx, src/launcher/features/apps/__snapshots__/AppList.test.tsx.snap, src/main/windows.ts, src/test/testFixtures.tsx
I have tested this with `&` and `=`. Only `&` would actually throw an error without this fix.
=> fix: use encodeUriComponent to handle special characters in path

Changelog.md, src/main/apps/app.ts, src/main/apps/apps.ts, src/main/apps/legacyMetaFiles.test.ts, src/main/apps/legacyMetaFiles.ts
Fixes https://nordicsemi.atlassian.net/browse/NCP-4000, https://trello.com/c/RQnktqXb.
Steps to reproduce the error:
1. Remove the folder %USERPROFILE%\.nrfconnect-apps (Windows) or ~/.nrfconnect-apps/ (macOS/Linux)
2. Run nRF Connect for Desktop 3.10 until it shows a list of apps. (Optional: install some apps, e.g. also the since then withdrawn Getting Started app)
3. Run nRF Connect for Desktop 4.1.1
=> Fix: Upgrading from 3.10 to 4.1

Changelog.minor.md, package.json, src/launcher/features/proxyLogin/ProxyErrorDialog.tsx, src/launcher/features/proxyLogin/ProxyLoginDialog.test.tsx, src/launcher/features/proxyLogin/ProxyLoginDialog.tsx, src/launcher/features/proxyLogin/__snapshots__/ProxyLoginDialog.test.tsx.snap, src/launcher/features/proxyLogin/proxyLoginSlice.test.ts, src/launcher/features/proxyLogin/proxyLoginSlice.ts
Addresses one aspect of https://trello.com/c/PvzJV1fs
When a proxy requested authentication in multiple requests at the same time, only one request was actually continued after the user entered the credentials (or cancelled the login).
One way to reproduce the problem:
1. Add   https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/internal/apps.json   as a source, so that there are effectively two sources (internal and   official).
2. Turn on “Check for updates at startup”
3. Restart with a proxy that requires authentication
4. When asked for credentials, enter the correct credentials
Expected result:
- All sources are updated and on the settings page, the button ”Check  for updates can be clicked”
Actual result:
- Only one source is updated and on the settings page, the button …
=> Fix: Multiple requests with authenticated proxies

Changelog.minor.md, package.json, src/ipc/config.ts, src/launcher/features/apps/appsEffects.ts, src/launcher/features/initialisation/initialiseLauncherState.ts, src/launcher/features/launcherUpdate/launcherUpdateEffects.ts, src/launcher/features/proxyLogin/ProxyErrorDialog.tsx, src/launcher/features/proxyLogin/ProxyLoginDialog.tsx, src/launcher/features/proxyLogin/__snapshots__/ProxyErrorDialog.test.tsx.snap, src/launcher/features/proxyLogin/__snapshots__/ProxyLoginDialog.test.tsx.snap, src/launcher/features/sources/sourcesEffects.ts, src/launcher/features/usageData/usageDataEffects.ts, src/launcher/store.ts, src/main/apps/sources.ts, src/main/config.ts, src/main/net.ts, test-e2e/setupTestApp.ts
Addresses one aspect of https://trello.com/c/PvzJV1fs.
When cancelling the proxy authentication while getting the latest app infos at least two dialogs were shown:
- The `ProxyErrorDialog`
- An `ErrorDialog` for the sources that could not be updated
Now the second dialog is not shown any longer.
When clicking on “Check for updates” in the settings, the `UpdateCheckCompleteDialog` was also shown, wrongly stating that all apps are up to date. This is also not shown any longer.
Additionally the `ProxyLoginDialog` and `ProxyErrorDialog` were updated to the latest styles. They now look like this:
=> Fix dialogs when proxy requires authentication

Changelog.minor.md, src/ipc/apps.ts, src/main/apps/app.ts, src/main/windows.ts
This will let the apps specify an `html`-property in their `package.json` that will let the app decide how to start itself.
=> Add support for custom html from the app

Changelog.minor.md, package-lock.json, package.json, src/ipc/sources.ts, src/launcher/features/filter/filterSlice.ts, src/launcher/features/sources/AddSourceDialog.tsx, src/launcher/features/sources/sourcesEffects.ts, src/main/apps/sourceChanges.ts
Addresses https://trello.com/c/cYOI5gkg and https://trello.com/c/vqYYyynf:
Fixes several aspects of the “Add source” dialog:
- Leading and trailing whitespace is trimmed from the entered URL.
- The dialog now uses the common style.
- More expressive error messages for typical errors: 
- `source.json` not reachable at given URL
- source already exists
- trying to add the official source.
The dialog now looks like this:
Also sneaks in a small fix for the name filter for apps: There leading and trailing whitespace are now also ignored.
=> Fix adding sources

Changelog.minor.md, src/main/apps/createDesktopShortcut.ts, src/main/argv.ts, src/main/browser.ts
To reproduce:
1. Determine an app (e.g. DTM) which is not installed when running the   launcher normally, with default directories.
2. Start the launcher with the options `--user-data-dir` and   `--apps-root-dir`, e.g. on macOS with `--user-data-dir /tmp/nrf_data --apps-root-dir /tmp/nrf_apps`.
3. The launcher open without any apps installed. Install one and create   a shortcut to it.
4. Open the shortcut.
Previously the app didn't open, instead an error message was shown: “Error when starting application – Error: Tried to open app …, but it is not installed”. Now the app opens correctly.
=> Fix shortcuts with differing directories

src/ipc/infrastructure/mainToRenderer.ts
This is relevant for the quickstart app and should technically be handled anyway. The invoke handler for this is exposed and an app can be started without ever opening/registering a launcher window.
=> fix: handle launcherWindow undefined

tsconfig.json
The old config only worked if pc-nrfconnect-shared is found top level in the node_modules folder directly in this project. In some cases it is found in other places, e.g. when using npm workspaces. The new config is shorter and uses the npm module resolution mechanism, so the tsconfig will be found in more places.
=> Use more flexible tsconfig location

Changelog.md, resources/css/launcher.scss, src/launcher/features/apps/AppList.test.tsx, src/launcher/features/apps/AppList.tsx, src/launcher/features/apps/__snapshots__/AppList.test.tsx.snap, src/launcher/features/filter/UpdateAllApps.tsx, src/launcher/features/localAppInstall/DropZoneForLocalApps.tsx, src/launcher/features/localAppInstall/dropZoneInfo.module.scss, src/launcher/features/proxyLogin/ProxyErrorDialog.tsx, src/launcher/util/Link.tsx, tailwind.config.js
For https://nordicsemi.atlassian.net/browse/NCD-90:
It is confusing to users, if no apps at all are shown. This PR changes this and shows a short information about the reasons in two cases:
If the filters are set in such a way that all apps are filtered out, a message is shown that the users need to change the filter (This also happens if the users have selected only a single source to be shown in the filter and then remove that source completely in the settings pane):
If no information about the apps was loaded from the server yet. This rarely happens but if it does it can be critical. This case usually only happens while users start nRF Connect for Desktop the very first time. But even then we do not want to shortly flash a misleading help text, for potentially the fraction of a second. …
=> Show empty apps list help

Changelog.minor.md
The bump entry was wrongly placed (not in “Changed” and right in the middle of an entry describing a bug and how to reproduce it.)
=> Fix changelog entry

Changelog.minor.md, package.json
These builds were never distributed/released. They take a lot of time to build, and seemingly noone uses them.
=> Remove tar gz from the linux builds.

src/ipc/apps.ts, src/ipc/persistedStore.ts, src/launcher/Root.tsx, src/launcher/features/apps/appsSlice.ts, src/launcher/features/quickstart/QuickstartDialog.tsx, src/launcher/features/settings/settingsSlice.ts, src/main/windows.ts
When the users close the dialog, it is now shown again.
=> Show dialog informing about the Quickstart app

Changelog.minor.md, src/launcher/features/apps/AppListEmpty.tsx, src/launcher/features/apps/__snapshots__/AppList.test.tsx.snap
Fixes https://nordicsemi.atlassian.net/browse/NCD-324.
The empty list state should be styled differently in three regards:
- The background should not be white any longer but transparent.
- The text should be split up by sentences.
- The sentences should be horizontally centred.
This is how it looked before:
This is how it looks now:
This is how it looks if no apps could be loaded yet:
And this is how the rare edge case looks if no apps could be loaded yet and the startup check is disabled:
Splitting up by sentence of course can mean that if the window gets too narrow, the sentence can get a line break in it. But this rarely happens and then still looks ok. E.g. this is the last window when resized to be just 400px wide:
=> Style: Empty apps list

Changelog.md, src/main/menu.ts
This is especially important on macOS, where this adds the standard list of all open windows for an app.
On macOS this can looks like this (before that whole menu was not there): 
On Windows and Linux those menus are usually not visible at all and only appear after pressing “alt”. Then it looks like this on Windows:
And similar on Linux:
=> Add the standard “Window” menu

package-lock.json
The newer version of electron was caused by a previous update to electron/remote. This caused a crash on ubuntu when the cursor entered the application window.
Currently this is just a fix for the crash but it does not stop this from happening again in the future. A more robust fix would be to have a version of electron required in the launcher. Given that shared is the one including electron, I have not done this yet to avoid confusion.
=> fix: change electron version

src/main/argv.test.ts, src/main/argv.ts, src/main/browser.ts, src/main/configureElectronApp.ts, src/main/windows.ts
The functions `openAppWindow`, `openDownloadableAppWindow`, and `openLocalAppWindow` had two parameters `openAppOptions` and `args` which serve a similar purpose and can never be specified at the same time. Now they are (again) merged into only a single parameter `args` and if there are `openAppOptions` they are earlier merged into `args`.
=> Rework app argument logic

pipelines/package/darwin.yml, pipelines/package/darwin_arm.yml
[NCD-505](https://nordicsemi.atlassian.net/browse/NCD-505):
According to https://www.electron.build/auto-update#quick-setup-guide the zip file is required for auto update to work on macOS.
=> Fix: Missing file necessary for macOS auto update

Changelog.minor.md, src/launcher/features/quickstart/QuickstartDialog.tsx
So far, the devices were hard coded in the launcher. If the Quick Start app started to support more devices, the launcher also had to be changed. Now the supported devices are read from the Quick Start app's package.json file.
The properties were added to the Quick Start’s `package.json` in https://github.com/NordicPlayground/pc-nrfconnect-quickstart/pull/129.
=> Show actual devices supported by Quick Start app

Changelog.minor.md, jest.config.js, package-lock.json, package.json, src/launcher/features/apps/appsEffects.ts, src/launcher/features/launcherUpdate/__snapshots__/UpdateAvailableDialog.test.tsx.snap, src/launcher/features/launcherUpdate/__snapshots__/UpdateProgressDialog.test.tsx.snap, src/launcher/features/proxyLogin/__snapshots__/ProxyErrorDialog.test.tsx.snap, src/launcher/features/proxyLogin/__snapshots__/ProxyLoginDialog.test.tsx.snap, src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap, src/launcher/features/sources/__snapshots__/ConfirmRemoveSourceDialog.test.tsx.snap
[NCD-602](https://nordicsemi.atlassian.net/browse/NCD-602): When installing downloadable apps fails, the users got to see the name of the IPC channel invoked, which looks rather cryptic. This happens often enough that I want to make this more user friendly. Now:
- There is first just the easier to understand message “Unable to install downloadable app.”
- An additional “Show technical details” section which, when clicked on, shows the error messages that causes the failure, but without the redundant IPC channel name.
More visually, this was the error dialog before:
This is how it looks now:
And with expanded details:
Because this also updates shared, the updated and corrected dialog styles from [v146](https://github.com/NordicSemiconductor/pc-nrfconnect-shared/releases/tag/v146) are also …
=> Enhance message when installing downloadable apps fails

Changelog.minor.md, package-lock.json, package.json, src/main/windows.ts
Fixes two problems:
When spawning the nrfutil process fails in certain ways, an uncaught exception in the main process got thrown.
The “certain ways” make this a bit hard to reproduce: On macOS this happened, when the nrfutil executable did not have the executable file mode. Usually this should not happen, because we set that mode ourselves correctly.
This resulted in an ugly dialog, outside of the launcher getting displayed by electron:
When during shutdown some process still tries to send IPC messages to the launcher window, an exception was thrown, which was presented to users as an ugly dialog.
To reproduce this, start to install a particular large app (nPM is the best for this). While the download is still ongoing, quit the launcher. A dialog like this was shown:
=> Fix: Some errors in native dialogs

.github/workflows/labels.yml, Changelog.minor.md
- Amend minor changelog
- Use the label checker from shared
- Do not forget about a failed label check on subsequent pushes
=> Minor changelog and Label checker

package-lock.json, package.json
It would previously fail to load new apps with updated shared and more supported devices
=> fix: update shared with updated packagejson types to remove error

Changelog.minor.md, src/main/apps/legacyMetaFiles.ts
This PR address an issue where an error is show when an app.json is being converted and one or more app that existed in apps.json is no longer installed.
Also @datenreisender should we consider deleting apps.jon after converting it?
=> Fix: Check if app is truly installed befare reading package.json

Changelog.minor.md, src/launcher/features/settings/Settings.tsx, src/main/apps/sourceChanges.ts, src/main/apps/sources.ts
Didn't happen in practice, but if a source URL contained the string `apps.json` or `source.json` somewhere in the middle, it would wrongly be replaced. E.g. https://source.json.example.org/source.json would not be handled correctly.
=> Fix: Strange source URLs could be handled wrong

Changelog.minor.md, doc/docs/download_cfd.md
The link in https://docs.nordicsemi.com/bundle/nrf-connect-desktop/page/download_cfd.html#using-behind-proxy is currently broken. This change should fix that.
=> Fix: Broken link to the proxy settings docs

.github/renovate.json
Because the label `ui not required`/`ui required` is also checked by a GitHub action now and we do not want a failure from that on every renovate PR.
=> Add `ui not required` label on renovate PRs 

src/ipc/persistedStore.ts, src/launcher/Root.tsx, src/launcher/features/appleSilicon/AppleSiliconAlert.tsx, src/launcher/features/appleSilicon/AppleSiliconDialog.tsx, src/launcher/features/appleSilicon/appleSiliconEffects.ts, src/launcher/features/appleSilicon/appleSiliconSlice.ts, src/launcher/features/quickstart/QuickstartDialog.tsx, src/launcher/store.ts
Show warning on Apple silicon machines using Intel build that this is not supported
=> Feat: show depreciation warning

Changelog.md, src/main/apps/createDesktopShortcut.ts
Surrounding ' or " didn't fix the issue for me
=> fix: having spaces in electron path now doesn't make path unusable

doc/docs/download_cfd.md
Rewrote the first line of the download page to have the installation in steps, for extra clarity.
Reported by @avalei as feedback from Zoomin.
=> doc: installation: make install steps more evident

doc/docs/download_cfd.md
Added mention of libfuse2 for Ubuntu.
Aligned formatting and phrasing with nRF Util section. NCD-902.
----
Related nRF Util PR: https://github.com/NordicSemiconductor/nrfutil-rs/pull/2088
=> doc: requirements: add libfuse2

Changelog.md, doc/docs/download_cfd.md
#1040 was labeled as “doc not required” but the J-Link version is actually mentioned in the docs, so it needs to be updated.
Also, the wording in the changelog was a bit off, so also updated that.
=> Fix: J-Link update to 7.94i

src/launcher/features/quickstart/QuickstartDialog.tsx
This was outdated anyway but is now fairly irrelevant due to quickstart supporting most devices
=> feat: remove mention of supported devices is quickstart dialog

Changelog.minor.md, src/main/configureElectronApp.ts
Because `nrfutilInAppPath` is always a string containing something, `installedNrfutilOlderThenBundledNrfutil` was always truthy, causing nrfutil to be always overwritten by the bundled version.
=> Fix `nrfutil` always being overwritten

src/launcher/util/appCompatibilityWarning.tsx
Since nrfutil-device 2.7 jlinkVersionDependency will also be defined when no J-Link is installed. But then jlinkVersionDependency.version will be undefined.
So this handles both cases correct if J-Link is not installed:
- For nrfutil-device < 2.7 jlinkVersionDependency will be undefined
- For nrfutil-device >= 2.7 jlinkVersionDependency.version will be undefined
=> Fix to also warn for nrfutil-device 2.7

Changelog.minor.md, build/getJlink.js, scripts/downloadFile.js
Only executed while building the launcher. J-Link is already uploaded to https://files.nordicsemi.com/ui/native/swtools/external/ncd/jlink/. The checksum files are not visible, but they can be fetched from the same location (e.g. https://files.nordicsemi.com/artifactory/swtools/external/ncd/jlink/JLink_Windows_V794i_x86_64.exe.sha256).
Part of [NCD-1110](https://nordicsemi.atlassian.net/browse/NCD-1110).
=> Get J-Link from Artifactory

package-lock.json, package.json, src/launcher/features/settings/Settings.tsx, src/main/apps/apps.ts, src/main/apps/dataMigration/legacyMetaFiles.test.ts, src/main/apps/dataMigration/legacyMetaFiles.ts, src/main/apps/dataMigration/migrateSourcesJson.test.ts, src/main/apps/dataMigration/migrateSourcesJson.ts, src/main/apps/sourceChanges.ts, src/main/apps/sources.test.ts, src/main/apps/sources.ts, src/main/fileUtil.ts, src/main/index.ts
For [NCD-1128](https://nordicsemi.atlassian.net/browse/NCD-1128):
Before we had an used a file `sources.json` which looked like this:
```json
{
"official": "https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/apps.json"
"Test": "https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/test/apps.json"
}
```
This change introduces that instead a `sources-versioned.json` is used instead, which will look like this:
```json
{
"v1": [
{
"name": "official",
"url": "https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/source.json"
},
{
"name": "Test",
"url": "https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/test/source.json"
}
]
}
```
If an existing `sources.json` is found it is left untouched but the content is migrated to a new `sources-versioned.json`. If an …
=> Add versioning to sources.json

Changelog.minor.md, build/bundleApps.js, src/launcher/features/apps/AppListEmpty.tsx, src/launcher/features/apps/__snapshots__/AppList.test.tsx.snap, src/main/apps/dataMigration/migrateSourcesJson.ts, src/main/apps/dataMigration/migrateSourcesVersionedJson.test.ts, src/main/apps/dataMigration/migrateSourcesVersionedJson.ts, src/main/apps/dataMigration/sourcesVersionedJsonV1.ts, src/main/apps/sources.ts, src/main/index.ts
Part of [NCD-791](https://nordicsemi.atlassian.net/browse/NCD-791):
- Instead of `developer.nordicsemi.com` use `files.nordicsemi.com` for the official source.
- On the first run migrate all sources which previously used `developer.nordicsemi.com` to now use `files.nordicsemi.com`.
- When running this version and then going back to an older version of the launcher, the older version will show apps installed from `developer.nordicsemi.com` as being withdrawn. But going forward to this version again, the app will look fine again.
=> Migrate currently used sources to `files.nordicsemi.com`

Changelog.md, Changelog.minor.md, src/common/persistedStore.ts, src/launcher/Root.tsx, src/launcher/features/initialisation/initialiseLauncherState.ts, src/launcher/features/settings/AddArtifactoryTokenDialog.tsx, src/launcher/features/settings/settingsEffects.ts, src/launcher/features/sources/AddLegacySourceWarning.tsx, src/launcher/features/sources/AddSourceDialog.tsx, src/launcher/features/sources/DeprecatedSourcesDialog.tsx, src/launcher/features/sources/MissingTokenWarning.tsx, src/launcher/features/sources/sourcesEffects.ts, src/launcher/features/sources/sourcesSlice.ts, src/launcher/features/telemetry/telemetryEffects.ts
Part of [NCD-791](https://nordicsemi.atlassian.net/browse/NCD-791):
When migrating from `developer.nordicsemi.com` to `files.nordicsemi.com` and people previously had added a source that now has restricted access, show them a special warning and describe how they can solve the issue:
The previous warning is shown only once, because people only migrate once from the old to the new server. But when you are **testing** this functionality, you might want to re-test it, in which case you need to edit your `config.json` and there remove the `wasWarnedOnMissingTokenAndMigratedSources` entry (or set it to `false`).
When users add a source which has restricted access and have not yet set a token, a similar warning is shown:
=> Show warnings on missing token for restricted sources

.github/workflows/build.yml, .github/workflows/labels.yml
Reason: I created several PRs which were initially not aimed at the main branch and so wrongly didn't cause the actions to run. And there is little harm for running the actions on all PRs, even if they may be unnecessary sometimes.
=> Do not restrict the PR triggers to the main branch

doc/docs/index.md
Rephrased the TCM app entry in the app list to mention deprecation from the NCS v3.0.0. NCD-1240.
=> doc: deprecate the TCM app

doc/docs/os_support.md
Linux Ubundu 20.04 LTS x64 to Not supported.
Requested by Quan Nguyen.
=> doc: os_support: Update table

build/bundleApps.js, src/common/legacySource.test.ts, src/common/legacySource.ts, src/launcher/features/sources/sourcesEffects.ts, src/main/apps/dataMigration/migrateSourcesVersionedJson.test.ts, src/main/apps/sources/sources.ts, src/main/net.test.ts, src/main/net.ts
Implements [NCD-1289](https://nordicsemi.atlassian.net/browse/NCD-1289):
When accessing Artifactory we have to use the download API, so instead of using a more simple URL like 
> `https://files.nordicsemi.com/artifactory/swtools/external/ncd/apps/3.7-apps/source.json` 
we have to use 
> `https://files.nordicsemi.com/ui/api/v1/download?isNativeBrowsing=false&repoKey=swtools&path=external/ncd/apps/3.7-apps/source.json`
But the latter is more cumbersome, e.g. reads worse when it appears in error dialogs. And some folks might  copy the shorter URLs from Artifactory (where they are shown as "File URL") and expecting them to work.
This PR makes the shorter URLs work in the launcher, by detecting them in `net.ts` and replacing them with URLs using the download API.
=> Support simpler Artifactory URLs

src/launcher/features/initialisation/initialiseLauncherState.ts, src/launcher/features/settings/AddArtifactoryTokenDialog.tsx, src/launcher/features/settings/Cards/Authentication.tsx, src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx, src/launcher/features/settings/Settings.tsx, src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap, src/launcher/features/settings/settingsSlice.ts, src/launcher/features/sources/MissingTokenWarning.tsx
Mitigates some of [NCD-1287](https://nordicsemi.atlassian.net/browse/NCD-1287):
The button to remove the Artifactory token was renamed from “Forget” to “Remove”. “Forget” was a strange and rather unusual term, which might confuse people:
After clicking on that button, the token was previously just removed, without informing the users of the consequence. This is now changed. If the user does not have any sources added which require the token now this dialog is shown:
If, more grave, the user also has non-external sources added which require the token, then those are listed and the situation is also explained:
Also did some small rewordings, especially purged all mentions of “Artifactory” since we didn't want to reflect this in the UI.
=> Enhance UX around removing tokens

src/common/legacySource.ts, src/common/persistedStore.ts, src/common/sources.ts, src/ipc/sources.ts, src/launcher/features/apps/App/App.tsx, src/launcher/features/apps/appsSlice.ts, src/launcher/features/filter/filterSlice.ts, src/launcher/features/initialisation/initialiseLauncherState.ts, src/launcher/features/settings/Cards/AppSources.tsx, src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx, src/launcher/features/sources/MissingTokenWarning.tsx, src/launcher/features/sources/sourcesEffects.ts, src/launcher/features/sources/sourcesSlice.ts, src/main/apps/app.ts, src/main/apps/appResource.ts, src/main/apps/apps.ts, src/main/apps/createDesktopShortcut.ts, src/main/apps/dataMigration/legacyMetaFiles.ts, src/main/apps/sources/sourceChanges.ts, src/main/apps/sources/sourceJson.ts, src/main/apps/sources/sources.ts, src/main/apps/sources/sourcesVersionedJson.ts, src/main/apps/sources/withdrawnJson.ts, src/main/argv.ts, src/main/config.ts, src/main/windows.ts, src/test/testFixtures.tsx
Group of smallish changes:
- When users habe non-public sources and no token, we used to warn them only once. Now we warn them on every startup.
- But we add a “Do not remind me again” button to that, so they can get rid of the warning if they want to.
- If we do not have a token, we do not try to load updates for non-public any longer, since we anyhow know that it will fail and we informed the users about this before.
- When a user has no token, tries to add a non-public source, and then cancels the request to enter a token in the missing token warning, we previously still tried to load that source. Because of the missing token this always failed and lead to an error message and the source not being added. Now we do not even try to load the source, sparing the user from the error message …
=> Artifactory: Update missing token warning

src/main/net.ts
When accessing public resources, we do not need to use the token. This especially has advantages if the token is not usable any longer, e.g. because it expired or was revoked. In those cases, the launcher would previously show an even when trying to load the official source, because it was using the invalid token.
=> Do not use token for public resources

src/common/sources.ts, src/launcher/features/initialisation/initialiseLauncherState.ts, src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx, src/launcher/features/sources/DeprecatedSourcesDialog.tsx, src/launcher/features/sources/sourcesSlice.ts, src/main/apps/sources/sources.ts
Fixes [NCD-1318](https://nordicsemi.atlassian.net/browse/NCD-1318):
Hide deprecated sources from the “Missing token” and “Remove token” dialogs. 
Also, do not ask for updates to deprecated sources on the server (which would fail anyhow). To reflect this, the “Remove deprecated sources” dialog was also reworded a bit:
=> Fix: Asking for token for deprecated sources

src/common/legacySource.test.ts, src/common/legacySource.ts, src/main/net.ts
This error was introduced when switching to also supporting short Artifactory URLs. In the files on the server we still use URLs with the download API (so they also work with old versions of the launcher). But when it comes to detect which apps are installed locally, we also compare these URLs, so they have to be identical in the case we migrate here.
STR:
1. Run launcher 5.1.0
2. Add Direction Viewer source https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/directionfinding/source.json
3. Install the Direction Viewer app
4. Run launcher 5.2.0
5. Set token
ER:
- Direction Viewer app shown as still normally installed (and being able to reinstall)
AR:
- Direction Viewer app shown as “not available for download anymore” (and if it is uninstalled, it vanishes, so it is impossible to …
=> Fix: Migrating sources

src/main/configureElectronApp.ts
Always copy bundled `nrfutil` to user data dir.
Rationale: If a future launcher contains a `nrfutil` executable which does not work properly (like we see coming up for Ubuntu 20.04), we want to enable users to get back to a working launcher by installing an old launcher which still contains a working `nrfutil` executable. This is only possible if we always copy the bundled `nrfutil`, even if it is already there.
=> Harden against future broken nrfutils

src/main/apps/sources/withdrawnJson.test.ts, src/main/apps/sources/withdrawnJson.ts
When jumping back and forth between launcher versions that use developer.nordicsemi.com and files.nordicsemi.com, apps may be incorrectly shown as withdrawn.
This is caused by them coming from different URLs on both servers, e.g. https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/release-test/pc-nrfconnect-npm.json on the old and
https://files.nordicsemi.com/artifactory/swtools/internal/ncd/apps/release-test/pc-nrfconnect-npm.json on the new one.
The fix here is to only compare the last segment of the URL.
=> Fix apps wrongly shown as withdrawn

Changelog.minor.md, src/main/open.ts
`openFile` and `openUrl` did not pass through when the underlying async functions (e.g. `shell.openPath`) finished. This was not used anywhere, but this change at least opens up the possibility of using that in the future.
=> Fix: Asynchronicity of `openFile` and `openUrl`

Changelog.minor.md, build/bundleApps.js, package-lock.json, package.json, src/launcher/util/appCompatibilityWarning.tsx, src/main/apps/app.ts, src/main/apps/appChanges.ts, src/main/nrfutilModules.ts
Accompanying PR to https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/1000
Handle if apps specify do or do not specify the version of nrfutil-core they require:
- Create their nrfutil sandbox in the right place
- Create the bundled nrfutil sandbox with the right path
=> Specify core version of nrfutil

.github/actions/build-action/action.yml, .github/workflows/build.yml, .github/workflows/build_darwin_arm64.yml, .github/workflows/build_darwin_x64.yml, .github/workflows/build_linux.yml, .github/workflows/build_win.yml
The names were too long in the GitHub Actions UI and the relevant platform name at the end was only partially visible.
=> Shorten workflow names

Changelog.minor.md, package.json
For [NCD-1389](https://nordicsemi.atlassian.net/browse/NCD-1389):
Because we want to change the used signature for the next release.
https://www.electron.build/electron-builder.interface.windowsconfiguration#verifyupdatecodesignature
This change will later be undone by #1153.
=> Disable signature verification on Windows

.github/workflows/continue-release-common.yml
When the release process is continued, the Windows executable was updated manually (which is why we interrupt the release). So we need to update the checksum in the release YAML file.
=> Fix Windows checksum

package.json, src/main/configureElectronApp.ts
Fixes a problem introduced in #1122.
`fs.cpSync` failed, when the source was in the asar archive. This only happened when running the binary, not when running from source because only in the binary an asar archive is used.
So now the files in nrfutil-sandboxes are unpacked from the asar archive to `app.asar.unpacked` and then copied from there.
=> Fix: Error when running binary

package-lock.json, package.json, src/common/sources.ts, src/ipc/apps.ts, src/launcher/features/apps/AppListEmpty.tsx, src/launcher/features/jlinkUpdate/JLinkUpdateDialog.tsx, src/launcher/features/jlinkUpdate/JLinkUpdateProgressDialog.tsx, src/launcher/features/jlinkUpdate/jlinkUpdateEffects.ts, src/launcher/features/jlinkUpdate/jlinkUpdateSlice.ts, src/launcher/features/launcherUpdate/UpdateAvailableDialog.tsx, src/launcher/features/launcherUpdate/launcherUpdateEffects.ts, src/launcher/features/process/initialiseLauncher.ts, src/launcher/features/process/thunkProcess.ts, src/launcher/features/process/updateProcess.ts, src/launcher/features/settings/Cards/Updates.tsx, src/launcher/features/sources/DeprecatedSourcesDialog.tsx, src/launcher/features/sources/MissingTokenWarning.tsx, src/launcher/features/sources/sourcesEffects.ts, src/launcher/features/telemetry/TelemetryDialog.tsx, src/launcher/features/telemetry/telemetryEffects.ts, src/launcher/index.tsx, src/launcher/util/appCompatibilityWarning.tsx, src/main/apps/apps.ts, src/main/apps/dataMigration/sourcesVersionedJsonV1.ts, src/main/apps/sources/sources.ts, src/main/argv.ts, src/main/registerIpcHandler.ts, test-e2e/launcher/basicBehaviour.spec.ts, test-e2e/launcher/installingApps.spec.ts, test-e2e/setupTestApp.ts
Extract the process concept from `initialiseLauncher` and also apply it to fetching update information (for J-Link, the launcher, and apps). Some other changes were needed for updating shared, but these should be collected in 7339122b4e1aef3c68b7001aed9525f6df60afb7.
=> Create a generic process concept

package-lock.json, package.json
Fixes [NCD-1460](https://nordicsemi.atlassian.net/browse/NCD-1460): When NCD was started from the GUI, J-Link was never detected.
=> Fix J-Link detection on macOS

Changelog.minor.md, scripts/getNrfutil.js
Before on macOS it always downloaded the universal variant.
=> Download arch specific variant of nrfutil

Changelog.minor.md, package-lock.json, package.json, src/ipc/apps.ts, src/main/apps/app.ts, src/main/windows.ts
Before, the fixed size of the Quick Start app was hard coded. With this, every app can specify its own fixed size by adding something like this to its package.json:
```json
"nrfConnectForDesktop": {
"fixedSize": {
"width": 800,
"height": 600
}
}   
```
=> Support fixed size apps
