lib/store/configureStore.js, lib/util/apps.js, lib/windows/app/index.js
Plugin is now passed to store which applies the middleware of the plugin if it provides one.
=> Using middleware optionally provided by plugin

lib/windows/loader/components/__tests__/AppListItem-test.jsx, lib/windows/loader/components/__tests__/AppListView-test.jsx, test/setup/jest-e2e.json
After the last PR was merged into master, some tests started failing. I have done some adjustments to make the tests work again.
=> Fix test failures on CI server

lib/api/core/index.js, lib/api/index.js, lib/util/apps.js, lib/windows/app/index.js
APP_INITIALIZE is dispatched right after the app is rendered, this way apps can know when everything is ready from Core's side, store/states/apis are ready to be used.
=> Added appInitializeAction()

lib/api/index.js, lib/windows/app/index.js
This mod is a prerequisite for the https://github.com/NordicSemiconductor/pc-yggdrasil/commit/dfbc718ea74daf87c455e7452b10dd2634f5a743
=> added api objects to module mapping for apps to import

README.md, lib/store/configureStore.js, lib/windows/app/actions/logActions.js, lib/windows/app/actions/serialPortActions.js, lib/windows/app/index.js
Took away api argument to dispatched actions, updated exposed api/module mapping and the documentation of it.
=> Api import

build/get-nrfjprog.js, package.json
The build started failing after the previous merge to master (#69). This PR fixes the issue.
=> Fix issues after upgrading dependencies

package.json
=> Fix react-infinite deprecation warnings

index.js, lib/windows/app/actions/mainMenuActions.js, lib/windows/app/containers/MainMenuContainer.js, package.json
About dialog can be accessed from MainMenu, it displays current app's name, version, description and nRFConnect's version. The dialog is modal to the app's window.
=> added about dialog

package.json
Upgrade pc-ble-driver-js. Also locking down pc-nrfconnect-devdep to the v1.0.0 tag.
=> Upgrade to pc-ble-driver-js v2.0.0

README.md, package.json
Updating README.md and package.json version number in preparation for v2.0.0 release.
=> Release v2.0.0

lib/api/jlink/jlinkFacade.js
This pull request is aim to fix the build server failure.
=> Fix build server failure

index.js, lib/windows/app/actions/logActions.js
Added feature to log some app related meta info to log file header.
=> Added app meta info to logfile header

package.json
- updated required modules
- modified effected win/mac related config to use earlier artifact name template
=> Added AppImage conf for electron-builder

apps.json
- Move npm location for nRF Cloud Gateway
- Clarify that this is an experimental app
=> Move npm location for nRF Cloud Gateway

lib/windows/app/components/DeviceSelector.jsx, lib/windows/app/containers/DeviceSelectorContainer.jsx
Minor adjustments to accomodate the latest changes to the nrf-device-lister API, ref: https://github.com/NordicSemiconductor/nrf-device-lister-js/pull/24.
=> Adjust to latest device lister API

README.md
Updated the supported devices in the README, and made some minor changes to the top paragraph.
=> Update supported devices

build/drivers/dfu_trigger_and_cdc_acm/nrfconnect_cdc_acm.inf
Left-over from #219, prompted by https://github.com/NordicSemiconductor/pc-nrfconnect-core/pull/218#pullrequestreview-127516652
This doesn't really change the behaviour of the driver installer (any other than updating the date) so I don't think any updates to the driver signatures *et al* will be needed until a final release.
=> Move around comments for the CDC ACM inf file

package.json
This update addresses https://github.com/NordicPlayground/pc-nrf-dfu-js/pull/33
=> Updated nrf-device-setup to 0.2.9, version to 2.4.0-rc.5

doc/repeated-usb-address-troubleshoot.md
Directly related to https://github.com/NordicSemiconductor/nrf-device-lister-js/pull/31
See also https://github.com/NordicPlayground/pc-nrf-dfu-js/pull/33
=> Add some documentation about the "Repeated USB addresses" problem

lib/windows/app/actions/deviceActions.js
This PR is due to fixing stop & start watching devices while switching mode.
Tested with selecting devices on
=> Fix stop & start watching devies

package.json
Simple fix for jest tests that got broken by jsdom/jsdom#2304
=> Fix tests for breaking issue of jsdom#2304

test/offline/oneOfficialAppInstalled-test.js, test/offline/oneOfficialAppNotInstalled-test.js, test/offline/oneOfficialAppUpgradable-test.js, test/setup/jest-e2e-offline.json, test/setup/jest-e2e-online.json, test/setup/jest-e2e.json
This PR updates UI snapshots expected wrt recent multi-source changes.
=> Fix e2e tests for recent multi-source changes

build/get-nrfjprog.js, build/installer.nsh
This PR is due to updating nrfjprog bingdings in core for linux and macOS.
=> Fix nrfjprog download

.github/ISSUE_TEMPLATE.md
The issue template points users towards using DevZone for posting issues.
=> Add issue template file with guidelines for posting issues

apps.json
This PR is due to updating Programmer name.
=> Update programmer name

build/get-nrfjprog.js, package.json
This PR is due to fixing downloading nrfjprog.
=> Fix nrfjprog downloading

build/get-nrfjprog.js, lib/api/index.js, lib/windows/app/index.js, package.json, webpack.config.js
This PR is due to update pc-nrfjprog-js module preventing logging related crashes experienced on Linux with PPK app.
=> Update pc-nrfjprog-js dependency 

.gitignore, README.md, azure-pipelines.yml, build/get-nrfjprog.js, build/installer.nsh, package.json
This PR is due to adding:
* Azure build config
* Azure release config
* Azure build status
* nrfjprog 64bit / 32bit support in installer
also due to fixing:
* tar.x() not extracting files to the right place
* Incorrect nrfjprog version in installer
=> Test azure

azure-pipelines.yml
This PR aims to fix windows builds on azure which silently swallows build and test commands.
=> Fix azure pipelines for windows

.gitignore, package.json
Test with pc-nrfjprog-js v1.5.1 and it works.
=> Test nrfjprog js

lib/windows/launcher/actions/desktopShortcutActions.js, main/fileUtil.js
This PR is due to fixing creating desktop shortcut on macOS. Some permission issues prevent it to create shortcuts. However, they have been solved in this PR.
=> Fix shortcut generation

azure-pipelines.yml, index.js, lib/components/HotkeyedDropdown.jsx, lib/windows/app/components/DeviceSelector.jsx, lib/windows/app/components/SerialPortSelector.jsx, lib/windows/app/components/__tests__/__snapshots__/DeviceSelector-test.jsx.snap, lib/windows/app/components/__tests__/__snapshots__/SerialPortSelector-test.jsx.snap, lib/windows/launcher/components/SettingsView.jsx, lib/windows/launcher/components/__tests__/__snapshots__/SettingsView-test.jsx.snap, resources/css/app.scss
- Fix About window exception
- Add mac code signing
- Fix device selector style/title/hotkey
=> Fix issues of found during release candidate tests

package.json
This PR is due to updating the latest version of png2icons.
=> Update png2icons to the latest

lib/windows/launcher/actions/desktopShortcutActions.js, main/fileUtil.js, package.json
This PR is due to creating different temp files to avoid permission issue on macOS.
=> Create different temp file to avoid permission issue

resources/css/app.scss, resources/css/brand19.scss
This PR is due to fixing support to select text in the log view.
=> Enable text selectable in log

apps.json
=> Update Getting Started Assistant project name

package.json
This PR is due to updating device setup version.
=> Update device setup version

azure-pipelines-internal.yml
This PR is due to adding internal release pipeline in core. No secret info is involved in the pipeline.
=> Add internal pipeline

Changelog.md
🤦‍♂️ These should have been added before, when I started the changelog in #388.
=> Fix: Add changelog entries for unreleased things

apps.json
This PR is due to releasing DTM. Please merge after publishing DTM.
=> Release DTM

Changelog.md
Describe changes from #369, #392, #393, #394.
Also group normal (user facing) and developer features.
=> Add missing changelog entries

Changelog.md
This belonged into #403 but I forgot it there. 🤦‍♂ 
Also moved the line regarding #370 because it describes a change, not a new feature.
=> Describe enhancement to error messages

package.json
This PR is to fix coping files from nrfjprog to build artifacts.
=> Remove filter

.gitignore, azure-pipelines.yml, build/entitlements.mac.plist, build/notarize.js, package.json
This PR aims to correct the build process on macOS.
Inspired by: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
=> Notarize macOS build

resources/css/launcher.scss, src/launcher/components/AppManagementFilter.jsx, src/launcher/components/AppManagementFilter.test.jsx
This implements [NCP-2992](https://projecttools.nordicsemi.no/jira/browse/NCP-2992) and some more:
- Reorder buttons in the filter bar: Filter and Search on the right, button to update all apps (if present) on the left.
- Rename button to update all apps.
- Sort source in the filter dropdown: Before the order of the sources was random and sometimes also changed. Now “Official” and “Local” are always at the top and the rest follows alphabetically sorted.
=> Enhance filter bar

azure-pipelines.yml, build/installer.nsh, package.json
This PR is to update JLink bundled on Windows.
=> Update bundled jlink on windows

src/launcher/reducers/releaseNotesDialogReducer.js, src/legacy/app/components/LogViewer.jsx
Fix linting issue and make code style consistent with other reducers.
=> Fix linting issue

Changelog-dev.md
This PR is to add changelog-dev.
=> Add changelog-dev

resources/css/launcher.scss
This PR fixes a small alignment issue, where the Apps and Settings text in the top navbar were not aligned with the other buttons.
=> Align top nav links to the centre

Changelog-dev.md, Changelog.md, package.json
Update version and changelogThis PR is
=> Update version and changelog

resources/app.html, src/app/index.jsx
This PR is a cosmetic update that fixes the glitch visible when loading new apps.
=> Fix app loader animation

package-lock.json, package.json, src/launcher/components/SettingsView.jsx, src/legacy/app/components/LogEntry.jsx
In tandem with the recent PR to shared, this replaces calls to moment.js with calls to date-fns.
=> Replace moment.js with date-fns

Changelog.md, README.md, apps.json, package.json, src/launcher/containers/AppManagementContainer.js
Prevented crash when incomplete regular expression is entered in search box
=> Prevent unsanitised regex crash

Changelog-dev.md, Changelog.md, resources/css/launcher.scss, src/launcher/components/AppIcon.jsx, src/launcher/components/__tests__/__snapshots__/AppManagementView-test.jsx.snap
When the icon for an app was missing, the layout broke because of cf869621.
=> Fix missing icon replacement

Changelog-dev.md, package-lock.json, package.json
For https://trello.com/c/IHlj9mlX/119-fix-layout-issue-introduced-for-the-toolchain-manager:
Upgrade to [4.25.0 of shared](https://github.com/NordicSemiconductor/pc-nrfconnect-shared/releases/tag/v4.25.0). This fixes the layout problem introduced by the Card component which manifested in the Toolchain Manager.
Because we did not release the version with the bug to the public, there is no need to mention it in the changelog.
=> Update to shared 4.25.0

Changelog-dev.md, package-lock.json, package.json, webpack.config.js
For https://trello.com/c/1GZYvZ0g/139-update-dependencies, following https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/158.
=> Update to pc-nrfconnect-shared 4.26.0

Changelog.md
Add changelog entry for improved error UX when app installation is corrupt
=> Add changelog entry

src/launcher/actions/desktopShortcutActions.js, src/main/config.js
Signed-off-by: Pascal Pickel <Pascal.Pickel@nordicsemi.no>
=> fix: create shortcut in ~./local/share/applications for linux

src/launcher/index.js
Used to cause a slight flicker at startup
=> feat: apply filter before displaying app list

Changelog.md
=> Add changelog entries

Changelog.md, resources/css/launcher.scss, src/launcher/components/AppManagementFilter.jsx, src/launcher/components/Root.jsx
For now the supported shortcuts will be `ctrl + f`, `ctrl + e`,
and `ctrl + l` where all of them will focus the search field (do
exactly the same).
=> Add keyboard shortcuts to focus search field

Changelog.md, resources/css/launcher.scss, src/launcher/components/AboutView.jsx, src/launcher/components/AppManagementFilter.jsx, src/launcher/components/AppManagementView.jsx, src/launcher/components/Root.jsx, src/launcher/components/__tests__/__snapshots__/AppManagementView-test.jsx.snap
On the image below the it's scrolled all the way to the top
See image above.
- I'm concerned that the changes done to position the scrollbar may make the code harder to maintain. This is due to additional container and wrapper added to the html, and the calculation of height to make the scrollbar visible. Furthermore, it introduces differences between the tabs, because two of them use scrollbar and one does not.
=> Fix scrollbar position and range of motion

azure-pipelines.yml
[Update macOS version in build pipelines](https://trello.com/c/DPNSBQRx/347-update-macos-version-in-build-pipelines).
=> Update build to latest macos

Changelog-dev.md, Changelog.md
Add the updated lib version to the dev changelog. And some minor cosmetics.
=> Update dev changelog

azure-pipelines.yml, build/installer.nsh, getJlink.js, package-lock.json, package.json
Build specifically for ia32 and x64 using electron builder.
=> Update jlink to support x64

test-e2e/launcher/fixtures/default/settings.json, test-e2e/launcher/fixtures/one-official-app-not-installed/.nrfconnect-apps/.gitignore, test-e2e/setupTestApp.ts
Small changes to make running the E2E tests more reliable.
=> Make E2E tests more reliable

package-lock.json, package.json
Fixes an error on macOS with the Audio DK.
=> Update `nrf-device-lib-js` to 0.4.8

Changelog.md, package-lock.json, package.json
On macOS the launcher froze for a few seconds (happened when usage data was enabled). Fixed by upgrading shared.
=> Fix: macOS freeze after launch

src/ipc/apps.ts, src/launcher/Root.tsx, src/launcher/features/apps/AppList.test.tsx, src/launcher/features/apps/appsEffects.ts, src/launcher/features/apps/appsSlice.ts, src/launcher/util/DropZoneForLocalApps.test.tsx, src/launcher/util/DropZoneForLocalApps.tsx, src/main/apps.ts, src/main/registerIpcHandler.ts, src/testrenderer.tsx
Install local applications by dropping the application package file onto the launcher window. This is still a basic implementation and will be enhanced later.
Part of https://trello.com/c/AvcUcoIb
=> Install local applications by drag & drop

package-lock.json, package.json, src/launcher/Root.tsx, src/launcher/features/apps/AppList.test.tsx, src/launcher/features/apps/AppList.tsx, src/launcher/features/settings/Settings.tsx, src/launcher/util/DropZoneForLocalApps.test.tsx, src/main/apps.ts
Some small enhancements, done while adding drag & drop support to installing local apps, but not closely related to it. So they went into this separate PR.
Part of https://trello.com/c/AvcUcoIb
=> Some enhancements

resources/css/launcher.scss
=> Fix stylings

package-lock.json, package.json
=> Rc v4.0.0 pre6

Changelog.md, package.json, src/launcher/features/apps/App/App.tsx, src/launcher/features/apps/App/InstallOtherVersion.tsx, src/launcher/features/apps/AppList.tsx, src/launcher/features/apps/ConfirmLaunchDialog.tsx, src/launcher/features/apps/InstallOtherVersionDialog.tsx, src/launcher/features/apps/appDialogsSlice.test.ts, src/launcher/features/apps/appDialogsSlice.ts, src/launcher/features/apps/appsEffects.ts, src/launcher/features/apps/appsSlice.test.ts, src/launcher/features/apps/appsSlice.ts, src/launcher/features/usageData/usageDataEffects.ts, src/launcher/store.ts, src/main/apps/appChanges.ts
Implements https://trello.com/c/TOAlpQwy
https://user-images.githubusercontent.com/260705/233093255-b1480772-d53b-4174-bad4-4bb1d1fe4907.mov
=> Feature: Downgrade apps

src/ipc/persistedStore.ts, src/launcher/features/apps/appsSlice.ts
Implements https://trello.com/c/9IM0a33J
=> Persist date of last update check

package-lock.json, package.json, src/ipc/apps.ts
=> Use the shared app utility functions

Changelog.minor.md, externals.d.ts, package-lock.json, package.json, resources/css/launcher.scss, src/launcher/features/launcherUpdate/__snapshots__/UpdateAvailableDialog.test.tsx.snap, src/launcher/features/launcherUpdate/__snapshots__/UpdateProgressDialog.test.tsx.snap, src/launcher/features/proxyLogin/__snapshots__/ProxyErrorDialog.test.tsx.snap, src/launcher/features/proxyLogin/__snapshots__/ProxyLoginDialog.test.tsx.snap, src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap, src/launcher/features/sources/__snapshots__/ConfirmRemoveSourceDialog.test.tsx.snap, src/main/argv.ts, src/main/singeInstanceLock.ts
Fixes https://nordicsemi.atlassian.net/browse/NCD-296.
Fixes two issues:
- List entries had the wrong font size.
- The scrollbar was wrong.
You can see the dialog by going to the pane Settings and clicking on “Show agreement”. This is how the dialog looked before:
This is how it looks now:
=> Fix: Usage statistics dialog

scripts/esbuild-renderer.ts, scripts/esbuild.ts, src/launcher/features/apps/appsEffects.ts
- Suppress a warning on launch
- Correct the event sent when installing apps
=> Fix two small telemetry issues

package-lock.json, package.json, src/launcher/features/usageData/UsageDataDialog.tsx
Google Analytics → Microsoft Azure
=> Adapt telemetry to changed backend

.github/workflows/labels.yml
Any given PR should either have the doc_required or doc_not_required label.
=> All PRs require doc_* label

.github/workflows/labels.yml
Now this will keep failing even when new changes have been pushed, but will only write the comment once
=> Experiment with label action

package-lock.json, package.json
It was added for ppk but it can be imported directly there
ref: https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/commit/49b1399ee1a9c834503edf9f0adc95c83b5255fb
=> feat: remove archiver dependency

doc/docs/os_support.md
Updated supported OS table as per latest info.
NRFU-891.
=> doc: update os support table

doc/docs/os_support.md
Edited the introductory sentence.
=> doc: os support: fix phrasing

.github/workflows/zoomin-publish-dev.yml, .github/workflows/zoomin-publish.yml, doc/docs/index.md
Updated order and links in the table listing CfD apps.
=> doc: update app table and workflow names

Changelog.md, package-lock.json, package.json, src/app/module-loader.js, src/launcher/util/appCompatibilityWarning.ts, src/launcher/util/minimalRequiredAppVersions.ts
This PR remove the old JS Binding as the have been deprecated. 
Apps have been added to the minimal required version to show warning when app is not supported and is known not to work.
=> Feat: remove devicelib js bindings and add warning

Changelog.minor.md, package-lock.json, package.json, src/launcher/features/apps/App/App.tsx, src/launcher/util/formatTimestamp.ts, src/main/apps/appBundler.ts, src/main/apps/appChanges.ts
=> Display publish date for non-official sources

doc/docs/download_cfd.md, doc/docs/os_support.md
Added cross-links to installation.
Updated Linux and macOS installation reqs.
=> doc: add installation cross-links

doc/docs/os_support.md
Added macOS 15 and Linux - Ubuntu 24.04 LTS.
Removed macOS 10.15, macOS 11, macOS 12.
Source: Supported platorms page on Wayland's confluence.
=> doc: update OS support list

Changelog.md, package-lock.json, package.json, src/main/menu.ts
1) BaseWindow is passed instead of BrowserWindow
2) Docs advise to use "role" instead of implementing anything custom on click manually.
=> Update shared to 188

src/launcher/util/appCompatibilityWarning.test.ts, src/launcher/util/appCompatibilityWarning.tsx
On Windows running `nrfutil` repeatedly for each app and also before launching an app made the UX too slow. Especially when launching an app there was easily a 1-2 second delay.
Now the result of asking for the required J-Link version is memoised per version of nrfutil-device. For most users this means this will be called only once or at most a few times and especially not again when launching an app.
A small consequence by this: Before the users could e.g. install J-Link and then try to launch an app again (even though the dialog said otherwise). Now users _must_ really reload the launcher for the launcher to detect the newly installed J-Link version.
=> Fix slow J-Link check on Windows

Changelog.minor.md, src/ipc/artifactoryToken.ts, src/ipc/persistedStore.ts, src/launcher/features/initialisation/initialiseLauncherState.ts, src/launcher/features/releaseNotes/ReleaseNotesDialog.tsx, src/launcher/features/settings/AddArtifactoryTokenDialog.tsx, src/launcher/features/settings/Settings.test.tsx, src/launcher/features/settings/Settings.tsx, src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap, src/launcher/features/settings/settingsSlice.ts, src/launcher/features/sources/AddSourceDialog.tsx, src/main/artifactoryToken.ts, src/main/artifactoryTokenStorage.ts, src/main/net.ts, src/main/registerIpcHandler.ts
[NCD-794](https://nordicsemi.atlassian.net/browse/NCD-794): Add support for Artifactory tokens
=> Artifactory tokens

src/launcher/features/settings/Cards/ChineseAppServer.tsx, src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
=> Change wording of Chinese app server setting

src/launcher/features/settings/AddArtifactoryTokenDialog.tsx, src/launcher/features/settings/Cards/Authentication.tsx, src/launcher/features/settings/Cards/ChineseAppServer.tsx, src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx, src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap, src/launcher/features/sources/AddLegacySourceWarning.tsx, src/launcher/features/sources/MissingTokenWarning.tsx
See the individual commits for descriptions
=> Small enhancements to the 5.2.0 wording adjustments

src/main/browser.ts, src/main/windows.ts
Fixes [NCD-777](https://nordicsemi.atlassian.net/browse/NCD-777):
New minimal width is 600 (minimal height is 500).
=> Min width of launcher was much too small

doc/docs/overview_cfd.md, doc/mkdocs.yml
Updated authentication to identity where appropriate. Reported by @datenreisender
=> doc: identity token: align header

Changelog.md, package.json, src/ipc/launcherUpdate.ts, src/launcher/features/settings/Cards/ChineseAppServer.tsx, src/main/launcherUpdate.ts, src/main/registerIpcHandler.ts
Also respect if users chose to use the Chinese server.
This was the last bit, where the launcher was still downloading anything from Github.
=> Use Artifactory for auto-updating the launcher

Changelog.minor.md, src/common/artifactoryUrl.test.ts, src/common/artifactoryUrl.ts, src/common/legacySource.ts, src/common/sources.ts, src/launcher/features/sources/sourcesEffects.ts, src/launcher/features/sources/sourcesSlice.ts, src/main/apps/sources/sources.ts, src/main/net.ts
In `src/common/artifactoryUrl.ts`.
=> Collect knowledge on Artifactory URLs

.github/workflows/build.yml, .github/workflows/build_darwin.yml, .github/workflows/build_linux.yml, .github/workflows/build_win.yml, .github/workflows/release-common.yml, .github/workflows/release-rc.yml, .github/workflows/release.yml
Part of [NCD-1051](https://nordicsemi.atlassian.net/browse/NCD-1051)
This is a lot different from the previous release process:
- It does some sanity checks before, e.g. if the version already exists.
- It extracts the version from the package.json file.
- It builds the release itself, instead of using the artifacts from a  previous workflow run.
- It creates a complete GitHub release, using the changelog, the  previous one only created a draft release.
- It also releases everything to Artifactory.
=> Do production releases to Artifactory 

doc/docs/revision_history.md, doc/docs/working_with_authentications_tokens.md
Added a mention of the safeStorage.
NCD-1319.
=> doc: tokens: mention safeStorage

doc/docs/download_cfd.md, doc/docs/revision_history.md, doc/mkdocs.yml
Updated the additional requirements section.
NCD-1445.
=> doc: installation: J-Link legacy drivers
